; HEADER_BLOCK_START
; generated by OrcaSlicer 2.2.0 on 2025-06-04 at 11:42:33
; total layer number: 1
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 140x140 1064
; iVBORw0KGgoAAAANSUhEUgAAAIwAAACMCAYAAACuwEE+AAAC5ElEQVR4Ae3dsW3jQBAFUBbkIi53BW
; 7DidJLlKkHBapAFbg0H2jAOIKQLXG1JGd33gM+cKmBub9Dr0QPAwAAAAAAAAAAAAAAQCovLy9/Brjn
; 7e3t7/V6/Rwz/nuAn0yH5TvH4/FjgKlbgzIfGkcUX+4NyzSOqMTGxhib49Fh0TaJLWkVbZNcjWGxEC
; dQc1DmcUR1Zs1hcUR1ZPyfv/agWIg7sUWraJtO7Dks2qYhEQZlHkMTVMRhmbbNQAyRB8URFUwrwzKN
; hXgHpfdA2iahFltF2+ykp2GZts1AXT0OyjyOqEoyDMt3HFFPaH2xLY2FuECmVtE2TzIsV23zCIPycw
; zNjGG5H0fUYFCWJvURZVjKk65tMj4u106KttEq9dNt2xiW9dLVfZRB2S7NH1GGZfs0eURlvQeKkqYW
; Yq0SJ+HbxrDES8iF2KDET5gjyrC0k12PqK2/6C51sstCrFXaz2ZtY1j6yaptY1D6TfW2MSz9p8rjt0
; HJNzTFR5RhyZtFR5R7IBnzUNtoFZnn17YZJ+pyuTT1A8m6eeh4ciTJ+/v7sqem19dXx1PSFP9exgKc
; K6fT6XOo4XA4fLT0g8vyVP9tr4W4z5zP53U/K6Nt+slmN9Y+C2NYiliI20u1xbaU3w63kzDfIrAQx8
; 7qi20pC3G8hP9ukrYxLEUsxPtl8T1QFBbi7dP8+2IcUdtk98fl2izE66Xbt1Bpm/pJ8VZNbfN8ml1s
; S/mAVnlSv+TZ4/fj6W6xLeXx+368On7GQnw7Ye+BorAQ/49WeZAPaBmWIhkX4nSPy7X5I6Es1vtCPC
; 62A/X1uBBrlZX11DaGZUMtt43Fdict3kdplZ218sIA90DBRD6itEpQ0RZi90CNiNA2WqUxe95HGZaG
; bbkQW2w7scV9lFbpzFoLscW2czUXYq2SRI22MSwJlSzE7oGSW3IfpVX4cu8+yuMyN91aiLUKv5ouxB
; 6XAQAAAAAAAAAAAAAA4KZ/Yu4wU8U/g+sAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 408
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA+UlEQVR4Ae2YwQ3DIAxFGShDdI2swY
; VrL8zBgQmYIKO14oBEUYICBGNX/0mWqp5+/L+FQSkAAABgAtu2vUIIH2vtEX8rSez7/o7i84r/KQnE
; jpfiU7F246zrV8XOjRbxuRtqNT3C2URqVPyySMWO1QaVtRtPdp3cDQrxUwacUnhZw5FaKX4oUmmP4V
; JNA86h691ucBZfdUOC8LJ+PoJb5u/UaZxmnLAkwv9miPNIcXLDOdd3qIk9yEo3vPcyxedQRkr0Rjr9
; cjNrwLXWtHdksVfKnCfcYPFOZIw5xHT9ipZ9ivUzYy1S5IPai+jH3UQa8O49BgAAALjBF4+89dX6Zn
; pSAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=87.5,90 POLYGON=[[52.5,55],[122.5,55],[122.5,125],[52.5,125],[52.5,55]]
M73 P0 R8
M106 S0
M106 P2 S0
;TYPE:Custom
PRINT_START
G28
M141 S0
G0 Z50 F600
M190 S60
G28 Z
G29; mesh bed leveling ,comment this code to close it
G0 X0 Y0 Z50 F6000
M73 P52 R4
M191 S0
M109 S210
M106 P3 S255
M83
G4 P3000
G0 X40.9292 Y43.4292 Z5 F6000
M73 P53 R4
G0 Z0.2 F600
M73 P53 R3
G1 E3 F1800
G1 X125.929 E3.4 F3000
M73 P51 R4
G1 Y45.4292 E0.08 F3000
M73 P54 R3
M73 P52 R4
G1 X40.9292 E3.4 F3000
M73 P53 R4
G1 Y128.429 E3.32 F3000
M73 P53 R3
G1 X42.9292 E0.08 F3000
G1 Y46.4292 E3.28 F3000
G1 X52.9292 E-0.4 F3000
M73 P55 R3
M73 P54 R3
G1 E0.4 F3000
M106 P3 S255
G90
G21
M83 ; use relative distances for extrusion
SET_PRESSURE_ADVANCE ADVANCE=0.031; Override pressure advance value
M106 S0
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.8 F1800
;TIMELAPSE_TAKE_FRAME

;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500 ACCEL_TO_DECEL=250
G1 X47.846 Y50.738 F15000
G1 Z.6
G1 Z.2
M73 P55 R3
G1 E.8 F1800
;TYPE:Skirt
;WIDTH:0.5
G1 F3000
G1 X49.438 Y49.446 E.07635
G1 X52.5 Y48.658 E.11778
G1 X122.5 Y48.658 E2.60723
G1 X124.708 Y49.055 E.08357
G1 X126.64 Y50.195 E.08357
G1 X128.054 Y51.938 E.08357
G1 X128.842 Y55 E.11778
G1 X128.842 Y125 E2.60723
G1 X128.445 Y127.208 E.08357
M73 P56 R3
G1 X127.305 Y129.14 E.08357
G1 X125.562 Y130.554 E.08357
G1 X122.5 Y131.342 E.11778
G1 X52.5 Y131.342 E2.60723
G1 X50.292 Y130.945 E.08357
M73 P56 R3
G1 X48.36 Y129.805 E.08357
G1 X46.946 Y128.062 E.08357
G1 X46.158 Y125 E.11778
G1 X46.158 Y55 E2.60723
G1 X46.555 Y52.792 E.08357
G1 X47.695 Y50.86 E.08357
G1 X47.815 Y50.763 E.00572
G1 X48.148 Y51.039 F15000
G1 F3000
G1 X49.871 Y49.735 E.08047
G1 X52.5 Y49.115 E.10062
G1 X122.5 Y49.115 E2.60723
G1 X124.624 Y49.511 E.08047
M73 P57 R3
G1 X126.461 Y50.648 E.08047
G1 X127.765 Y52.371 E.08047
G1 X128.385 Y55 E.10062
G1 X128.385 Y125 E2.60723
G1 X127.989 Y127.124 E.08047
M73 P57 R3
G1 X126.852 Y128.961 E.08047
G1 X125.129 Y130.265 E.08047
G1 X122.5 Y130.885 E.10062
G1 X52.5 Y130.885 E2.60723
G1 X50.376 Y130.489 E.08047
G1 X48.539 Y129.352 E.08047
G1 X47.235 Y127.629 E.08047
G1 X46.615 Y125 E.10062
G1 X46.615 Y55 E2.60723
G1 X47.011 Y52.876 E.08047
G1 X48.127 Y51.073 E.07898
G1 X48.529 Y51.334 F15000
G1 F3000
M73 P58 R3
G1 X48.599 Y51.225 E.00483
G1 X50.3 Y50.038 E.07726
G1 X52.5 Y49.572 E.08376
G1 X122.5 Y49.572 E2.60723
G1 X124.536 Y49.968 E.07726
M73 P58 R3
G1 X126.275 Y51.099 E.07726
G1 X127.462 Y52.8 E.07726
G1 X127.928 Y55 E.08376
G1 X127.928 Y125 E2.60723
G1 X127.532 Y127.036 E.07726
G1 X126.401 Y128.775 E.07726
G1 X124.7 Y129.962 E.07726
G1 X122.5 Y130.428 E.08376
G1 X52.5 Y130.428 E2.60723
G1 X50.464 Y130.032 E.07726
G1 X48.725 Y128.901 E.07726
G1 X47.538 Y127.2 E.07726
G1 X47.072 Y125 E.08376
G1 X47.072 Y55 E2.60723
G1 X47.468 Y52.964 E.07726
M73 P59 R3
G1 X48.507 Y51.367 E.07094
G1 X48.9 Y51.638 F15000
G1 F3000
G1 X49.05 Y51.421 E.00981
G1 X50.724 Y50.357 E.0739
M73 P59 R3
G1 X52.5 Y50.029 E.06726
G1 X122.5 Y50.029 E2.60723
G1 X124.444 Y50.425 E.0739
G1 X126.079 Y51.55 E.0739
G1 X127.143 Y53.224 E.0739
G1 X127.471 Y55 E.06726
G1 X127.471 Y125 E2.60723
G1 X127.075 Y126.944 E.0739
G1 X125.95 Y128.579 E.0739
G1 X124.276 Y129.643 E.0739
G1 X122.5 Y129.971 E.06726
G1 X52.5 Y129.971 E2.60723
G1 X50.556 Y129.575 E.0739
M73 P60 R3
G1 X48.921 Y128.45 E.0739
G1 X47.857 Y126.776 E.0739
G1 X47.529 Y125 E.06726
G1 X47.529 Y55 E2.60723
G1 X47.925 Y53.056 E.0739
M73 P60 R3
G1 X48.878 Y51.671 E.0626
G1 X49.261 Y51.952 F15000
G1 F3000
G1 X49.499 Y51.628 E.01498
G1 X51.142 Y50.695 E.07039
G1 X52.5 Y50.486 E.05116
G1 X122.5 Y50.486 E2.60723
G1 X124.348 Y50.882 E.07039
G1 X125.872 Y51.999 E.07039
G1 X126.805 Y53.642 E.07039
G1 X127.014 Y55 E.05116
G1 X127.014 Y125 E2.60723
G1 X126.618 Y126.848 E.07039
M73 P61 R3
G1 X125.501 Y128.372 E.07039
G1 X123.858 Y129.305 E.07039
G1 X122.5 Y129.514 E.05116
G1 X52.5 Y129.514 E2.60723
G1 X50.652 Y129.118 E.07039
M73 P61 R3
G1 X49.128 Y128.001 E.07039
G1 X48.195 Y126.358 E.07039
G1 X47.986 Y125 E.05116
G1 X47.986 Y55 E2.60723
G1 X48.382 Y53.152 E.07039
G1 X49.238 Y51.985 E.05392
G1 X49.608 Y52.277 F15000
G1 F3000
G1 X49.946 Y51.848 E.02036
G1 X51.552 Y51.055 E.06669
G1 X52.5 Y50.943 E.03555
G1 X122.5 Y50.943 E2.60723
G1 X124.246 Y51.338 E.06669
M73 P62 R3
G1 X125.652 Y52.446 E.06669
G1 X126.445 Y54.052 E.06669
G1 X126.557 Y55 E.03555
G1 X126.557 Y125 E2.60723
G1 X126.162 Y126.746 E.06669
M73 P62 R3
G1 X125.054 Y128.152 E.06669
G1 X123.448 Y128.945 E.06669
G1 X122.5 Y129.057 E.03555
G1 X52.5 Y129.057 E2.60723
G1 X50.754 Y128.662 E.06669
G1 X49.348 Y127.554 E.06669
G1 X48.555 Y125.948 E.06669
G1 X48.443 Y125 E.03555
G1 X48.443 Y55 E2.60723
G1 X48.838 Y53.254 E.06669
M73 P63 R3
G1 X49.583 Y52.308 E.04484
G1 X49.938 Y52.612 F15000
G1 F3000
G1 X50.392 Y52.082 E.02598
G1 X52.5 Y51.4 E.08254
M73 P63 R3
G1 X122.5 Y51.4 E2.60723
G1 X124.138 Y51.795 E.06277
G1 X125.418 Y52.892 E.06277
G1 X126.1 Y55 E.08254
G1 X126.1 Y125 E2.60723
G1 X125.705 Y126.638 E.06277
G1 X124.608 Y127.918 E.06277
G1 X122.5 Y128.6 E.08254
G1 X52.5 Y128.6 E2.60723
G1 X50.862 Y128.205 E.06277
G1 X49.582 Y127.108 E.06277
G1 X48.9 Y125 E.08254
G1 X48.9 Y55 E2.60723
G1 X49.295 Y53.362 E.06277
M73 P64 R3
G1 X49.911 Y52.642 E.0353
G1 X50.244 Y52.957 F15000
G1 F3000
G1 X50.833 Y52.336 E.03191
G1 X52.5 Y51.857 E.06459
M73 P64 R3
G1 X122.5 Y51.857 E2.60723
G1 X124.023 Y52.251 E.05859
G1 X125.164 Y53.333 E.05859
G1 X125.643 Y55 E.06459
G1 X125.643 Y125 E2.60723
G1 X125.249 Y126.523 E.05859
G1 X124.167 Y127.664 E.05859
G1 X122.5 Y128.143 E.06459
G1 X52.5 Y128.143 E2.60723
G1 X50.977 Y127.749 E.05859
M73 P65 R3
G1 X49.836 Y126.667 E.05859
G1 X49.357 Y125 E.06459
G1 X49.357 Y55 E2.60723
G1 X49.751 Y53.477 E.05859
M73 P65 R2
G1 X50.216 Y52.986 E.02519
M73 P65 R3
G1 X50.519 Y53.312 F15000
G1 F3000
G1 X51.27 Y52.613 E.03821
G1 X52.5 Y52.314 E.04715
M73 P65 R2
G1 X122.5 Y52.314 E2.60723
G1 X123.898 Y52.707 E.05408
G1 X124.887 Y53.77 E.05408
G1 X125.186 Y55 E.04715
G1 X125.186 Y125 E2.60723
G1 X124.793 Y126.398 E.05408
M73 P66 R2
G1 X123.73 Y127.387 E.05408
G1 X122.5 Y127.686 E.04715
G1 X52.5 Y127.686 E2.60723
G1 X51.102 Y127.293 E.05408
G1 X50.113 Y126.23 E.05408
M73 P66 R2
G1 X49.814 Y125 E.04715
G1 X49.814 Y55 E2.60723
G1 X50.207 Y53.602 E.05408
G1 X50.49 Y53.339 E.01439
G1 X50.751 Y53.669 F15000
G1 F3000
G1 X51.698 Y52.921 E.04498
G1 X52.5 Y52.771 E.03037
G1 X122.5 Y52.771 E2.60723
G1 X123.761 Y53.162 E.04917
G1 X124.579 Y54.198 E.04917
M73 P67 R2
G1 X124.729 Y55 E.03037
G1 X124.729 Y125 E2.60723
G1 X124.338 Y126.261 E.04917
G1 X123.302 Y127.079 E.04917
G1 X122.5 Y127.229 E.03037
M73 P67 R2
G1 X52.5 Y127.229 E2.60723
G1 X51.239 Y126.838 E.04917
G1 X50.421 Y125.802 E.04917
G1 X50.271 Y125 E.03037
G1 X50.271 Y55 E2.60723
G1 X50.662 Y53.739 E.04917
G1 X50.719 Y53.694 E.0027
G1 E-.2 F1800
;WIPE_START
G1 F3000
G1 X51.504 Y53.074 E-.6
;WIPE_END
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 X56.865 Y58.507 Z.6 F15000
G1 X121.186 Y123.686 Z.6
G1 Z.2
M73 P68 R2
G1 E.8 F1800
;TYPE:Inner wall
G1 F3000
G1 X53.814 Y123.686 E2.50934
G1 X53.814 Y56.314 E2.50934
G1 X121.186 Y56.314 E2.50934
M73 P68 R2
G1 X121.186 Y123.626 E2.5071
G1 X121.643 Y124.143 F15000
M73 P69 R2
G1 F3000
G1 X53.357 Y124.143 E2.54339
G1 X53.357 Y55.857 E2.54339
G1 X121.643 Y55.857 E2.54339
G1 X121.643 Y124.083 E2.54115
M73 P70 R2
M73 P69 R2
G1 X122.1 Y124.6 F15000
;TYPE:Outer wall
G1 F3000
G1 X52.9 Y124.6 E2.57744
G1 X52.9 Y55.4 E2.57744
G1 X122.1 Y55.4 E2.57744
M73 P70 R2
G1 X122.1 Y124.54 E2.5752
M73 P71 R2
G1 E-.2 F1800
;WIPE_START
G1 F3000
G1 X121.1 Y124.541 E-.6
;WIPE_END
G1 X121.094 Y116.908 Z.6 F15000
G1 X121.049 Y57.379 Z.6
M73 P71 R2
G1 Z.2
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.501638
G1 F6300
G1 X120.327 Y56.657 E.03815
G1 X119.678 Y56.657 E.02425
G1 X120.843 Y57.822 E.06157
G1 X120.843 Y58.47 E.02425
G1 X119.03 Y56.657 E.09587
G1 X118.381 Y56.657 E.02425
G1 X120.843 Y59.119 E.13016
G1 X120.843 Y59.768 E.02425
G1 X117.732 Y56.657 E.16446
G1 X117.083 Y56.657 E.02425
G1 X120.843 Y60.417 E.19875
G1 X120.843 Y61.065 E.02425
G1 X116.435 Y56.657 E.23304
G1 X115.786 Y56.657 E.02425
G1 X120.843 Y61.714 E.26734
G1 X120.843 Y62.363 E.02425
G1 X115.137 Y56.657 E.30163
G1 X114.488 Y56.657 E.02425
G1 X120.843 Y63.012 E.33592
M73 P72 R2
G1 X120.843 Y63.66 E.02425
G1 X113.84 Y56.657 E.37022
G1 X113.191 Y56.657 E.02425
G1 X120.843 Y64.309 E.40451
G1 X120.843 Y64.958 E.02425
M73 P72 R2
G1 X112.542 Y56.657 E.4388
G1 X111.894 Y56.657 E.02425
G1 X120.843 Y65.606 E.4731
G1 X120.843 Y66.255 E.02425
G1 X111.245 Y56.657 E.50739
G1 X110.596 Y56.657 E.02425
G1 X120.843 Y66.904 E.54168
G1 X120.843 Y67.553 E.02425
G1 X109.947 Y56.657 E.57598
G1 X109.299 Y56.657 E.02425
G1 X120.843 Y68.201 E.61027
G1 X120.843 Y68.85 E.02425
G1 X108.65 Y56.657 E.64456
G1 X108.001 Y56.657 E.02425
G1 X120.843 Y69.499 E.67886
G1 X120.843 Y70.148 E.02425
G1 X107.352 Y56.657 E.71315
G1 X106.704 Y56.657 E.02425
G1 X120.843 Y70.796 E.74744
G1 X120.843 Y71.445 E.02425
G1 X106.055 Y56.657 E.78174
G1 X105.406 Y56.657 E.02425
G1 X120.843 Y72.094 E.81603
G1 X120.843 Y72.742 E.02425
M73 P73 R2
G1 X104.758 Y56.657 E.85033
G1 X104.109 Y56.657 E.02425
G1 X120.843 Y73.391 E.88462
G1 X120.843 Y74.04 E.02425
G1 X103.46 Y56.657 E.91891
M73 P73 R2
G1 X102.811 Y56.657 E.02425
G1 X120.843 Y74.689 E.95321
G1 X120.843 Y75.337 E.02425
G1 X102.163 Y56.657 E.9875
G1 X101.514 Y56.657 E.02425
G1 X120.843 Y75.986 E1.02179
G1 X120.843 Y76.635 E.02425
G1 X100.865 Y56.657 E1.05609
G1 X100.216 Y56.657 E.02425
G1 X120.843 Y77.284 E1.09038
G1 X120.843 Y77.932 E.02425
G1 X99.568 Y56.657 E1.12467
G1 X98.919 Y56.657 E.02425
G1 X120.843 Y78.581 E1.15897
G1 X120.843 Y79.23 E.02425
G1 X98.27 Y56.657 E1.19326
G1 X97.622 Y56.657 E.02425
M73 P74 R2
G1 X120.843 Y79.878 E1.22755
G1 X120.843 Y80.527 E.02425
G1 X96.973 Y56.657 E1.26185
G1 X96.324 Y56.657 E.02425
G1 X120.843 Y81.176 E1.29614
M73 P74 R2
G1 X120.843 Y81.825 E.02425
G1 X95.675 Y56.657 E1.33043
G1 X95.027 Y56.657 E.02425
G1 X120.843 Y82.473 E1.36473
G1 X120.843 Y83.122 E.02425
G1 X94.378 Y56.657 E1.39902
G1 X93.729 Y56.657 E.02425
G1 X120.843 Y83.771 E1.43331
G1 X120.843 Y84.42 E.02425
G1 X93.08 Y56.657 E1.46761
G1 X92.432 Y56.657 E.02425
G1 X120.843 Y85.068 E1.5019
G1 X120.843 Y85.717 E.02425
M73 P75 R2
G1 X91.783 Y56.657 E1.53619
G1 X91.134 Y56.657 E.02425
G1 X120.843 Y86.366 E1.57049
G1 X120.843 Y87.014 E.02425
G1 X90.486 Y56.657 E1.60478
M73 P75 R2
G1 X89.837 Y56.657 E.02425
G1 X120.843 Y87.663 E1.63908
G1 X120.843 Y88.312 E.02425
G1 X89.188 Y56.657 E1.67337
G1 X88.539 Y56.657 E.02425
G1 X120.843 Y88.961 E1.70766
G1 X120.843 Y89.609 E.02425
G1 X87.891 Y56.657 E1.74196
G1 X87.242 Y56.657 E.02425
G1 X120.843 Y90.258 E1.77625
G1 X120.843 Y90.907 E.02425
M73 P76 R2
G1 X86.593 Y56.657 E1.81054
G1 X85.945 Y56.657 E.02425
G1 X120.843 Y91.555 E1.84484
G1 X120.843 Y92.204 E.02425
G1 X85.296 Y56.657 E1.87913
M73 P76 R2
G1 X84.647 Y56.657 E.02425
G1 X120.843 Y92.853 E1.91342
G1 X120.843 Y93.502 E.02425
G1 X83.998 Y56.657 E1.94772
G1 X83.35 Y56.657 E.02425
G1 X120.843 Y94.15 E1.98201
G1 X120.843 Y94.799 E.02425
G1 X82.701 Y56.657 E2.0163
G1 X82.052 Y56.657 E.02425
M73 P76 R1
G1 X120.843 Y95.448 E2.0506
M73 P77 R1
G1 X120.843 Y96.097 E.02425
G1 X81.403 Y56.657 E2.08489
G1 X80.755 Y56.657 E.02425
G1 X120.843 Y96.745 E2.11918
M73 P76 R1
G1 X120.843 Y97.394 E.02425
M73 P77 R1
G1 X80.106 Y56.657 E2.15348
G1 X79.457 Y56.657 E.02425
G1 X120.843 Y98.043 E2.18777
G1 X120.843 Y98.691 E.02425
G1 X78.809 Y56.657 E2.22206
G1 X78.16 Y56.657 E.02425
G1 X120.843 Y99.34 E2.25636
G1 X120.843 Y99.989 E.02425
M73 P78 R1
G1 X77.511 Y56.657 E2.29065
G1 X76.862 Y56.657 E.02425
G1 X120.843 Y100.638 E2.32494
G1 X120.843 Y101.286 E.02425
G1 X76.214 Y56.657 E2.35924
M73 P78 R1
G1 X75.565 Y56.657 E.02425
G1 X120.843 Y101.935 E2.39353
G1 X120.843 Y102.584 E.02425
G1 X74.916 Y56.657 E2.42783
G1 X74.267 Y56.657 E.02425
G1 X120.843 Y103.233 E2.46212
G1 X120.843 Y103.881 E.02425
G1 X73.619 Y56.657 E2.49641
G1 X72.97 Y56.657 E.02425
M73 P79 R1
G1 X120.843 Y104.53 E2.53071
G1 X120.843 Y105.179 E.02425
G1 X72.321 Y56.657 E2.565
G1 X71.673 Y56.657 E.02425
G1 X120.843 Y105.827 E2.59929
M73 P79 R1
G1 X120.843 Y106.476 E.02425
G1 X71.024 Y56.657 E2.63359
G1 X70.375 Y56.657 E.02425
G1 X120.843 Y107.125 E2.66788
G1 X120.843 Y107.774 E.02425
M73 P80 R1
G1 X69.726 Y56.657 E2.70217
G1 X69.078 Y56.657 E.02425
G1 X120.843 Y108.422 E2.73647
G1 X120.843 Y109.071 E.02425
G1 X68.429 Y56.657 E2.77076
M73 P80 R1
G1 X67.78 Y56.657 E.02425
G1 X120.843 Y109.72 E2.80505
G1 X120.843 Y110.369 E.02425
G1 X67.131 Y56.657 E2.83935
G1 X66.483 Y56.657 E.02425
G1 X120.843 Y111.017 E2.87364
G1 X120.843 Y111.666 E.02425
M73 P81 R1
G1 X65.834 Y56.657 E2.90793
G1 X65.185 Y56.657 E.02425
G1 X120.843 Y112.315 E2.94223
G1 X120.843 Y112.963 E.02425
G1 X64.537 Y56.657 E2.97652
M73 P81 R1
G1 X63.888 Y56.657 E.02425
G1 X120.843 Y113.612 E3.01081
G1 X120.843 Y114.261 E.02425
G1 X63.239 Y56.657 E3.04511
G1 X62.59 Y56.657 E.02425
M73 P82 R1
G1 X120.843 Y114.91 E3.0794
G1 X120.843 Y115.558 E.02425
G1 X61.942 Y56.657 E3.1137
G1 X61.293 Y56.657 E.02425
G1 X120.843 Y116.207 E3.14799
M73 P82 R1
G1 X120.843 Y116.856 E.02425
G1 X60.644 Y56.657 E3.18228
G1 X59.996 Y56.657 E.02425
G1 X120.843 Y117.504 E3.21658
G1 X120.843 Y118.153 E.02425
M73 P83 R1
G1 X59.347 Y56.657 E3.25087
G1 X58.698 Y56.657 E.02425
G1 X120.843 Y118.802 E3.28516
G1 X120.843 Y119.451 E.02425
G1 X58.049 Y56.657 E3.31946
M73 P83 R1
G1 X57.401 Y56.657 E.02425
G1 X120.843 Y120.099 E3.35375
G1 X120.843 Y120.748 E.02425
G1 X56.752 Y56.657 E3.38804
G1 X56.103 Y56.657 E.02425
M73 P84 R1
G1 X120.843 Y121.397 E3.42234
G1 X120.843 Y122.046 E.02425
G1 X55.454 Y56.657 E3.45663
G1 X54.806 Y56.657 E.02425
G1 X120.843 Y122.694 E3.49092
M73 P84 R1
G1 X120.843 Y123.343 E.02425
G1 X54.157 Y56.657 E3.52522
G1 X54.157 Y57.306 E.02425
G1 X120.194 Y123.343 E3.49093
G1 X119.546 Y123.343 E.02425
M73 P85 R1
G1 X54.157 Y57.954 E3.45663
G1 X54.157 Y58.603 E.02425
G1 X118.897 Y123.343 E3.42234
G1 X118.248 Y123.343 E.02425
G1 X54.157 Y59.252 E3.38805
M73 P85 R1
G1 X54.157 Y59.901 E.02425
G1 X117.599 Y123.343 E3.35375
G1 X116.951 Y123.343 E.02425
G1 X54.157 Y60.549 E3.31946
G1 X54.157 Y61.198 E.02425
M73 P86 R1
G1 X116.302 Y123.343 E3.28516
G1 X115.653 Y123.343 E.02425
G1 X54.157 Y61.847 E3.25087
G1 X54.157 Y62.495 E.02425
G1 X115.005 Y123.343 E3.21658
M73 P86 R1
G1 X114.356 Y123.343 E.02425
G1 X54.157 Y63.144 E3.18228
G1 X54.157 Y63.793 E.02425
G1 X113.707 Y123.343 E3.14799
G1 X113.058 Y123.343 E.02425
M73 P87 R1
G1 X54.157 Y64.442 E3.1137
G1 X54.157 Y65.09 E.02425
G1 X112.41 Y123.343 E3.0794
G1 X111.761 Y123.343 E.02425
G1 X54.157 Y65.739 E3.04511
M73 P87 R1
G1 X54.157 Y66.388 E.02425
G1 X111.112 Y123.343 E3.01082
G1 X110.463 Y123.343 E.02425
G1 X54.157 Y67.037 E2.97652
G1 X54.157 Y67.685 E.02425
M73 P88 R1
G1 X109.815 Y123.343 E2.94223
G1 X109.166 Y123.343 E.02425
G1 X54.157 Y68.334 E2.90794
G1 X54.157 Y68.983 E.02425
G1 X108.517 Y123.343 E2.87364
M73 P88 R1
G1 X107.869 Y123.343 E.02425
M73 P88 R0
G1 X54.157 Y69.631 E2.83935
G1 X54.157 Y70.28 E.02425
G1 X107.22 Y123.343 E2.80506
G1 X106.571 Y123.343 E.02425
M73 P89 R0
G1 X54.157 Y70.929 E2.77076
M73 P88 R0
G1 X54.157 Y71.578 E.02425
G1 X105.922 Y123.343 E2.73647
G1 X105.274 Y123.343 E.02425
G1 X54.157 Y72.226 E2.70218
M73 P89 R0
G1 X54.157 Y72.875 E.02425
G1 X104.625 Y123.343 E2.66788
G1 X103.976 Y123.343 E.02425
G1 X54.157 Y73.524 E2.63359
G1 X54.157 Y74.173 E.02425
G1 X103.327 Y123.343 E2.59929
G1 X102.679 Y123.343 E.02425
M73 P90 R0
G1 X54.157 Y74.821 E2.565
G1 X54.157 Y75.47 E.02425
G1 X102.03 Y123.343 E2.53071
G1 X101.381 Y123.343 E.02425
G1 X54.157 Y76.119 E2.49641
M73 P90 R0
G1 X54.157 Y76.767 E.02425
G1 X100.733 Y123.343 E2.46212
G1 X100.084 Y123.343 E.02425
G1 X54.157 Y77.416 E2.42783
G1 X54.157 Y78.065 E.02425
G1 X99.435 Y123.343 E2.39353
G1 X98.786 Y123.343 E.02425
M73 P91 R0
G1 X54.157 Y78.714 E2.35924
G1 X54.157 Y79.362 E.02425
G1 X98.138 Y123.343 E2.32495
G1 X97.489 Y123.343 E.02425
G1 X54.157 Y80.011 E2.29065
M73 P91 R0
G1 X54.157 Y80.66 E.02425
G1 X96.84 Y123.343 E2.25636
G1 X96.191 Y123.343 E.02425
G1 X54.157 Y81.309 E2.22207
G1 X54.157 Y81.957 E.02425
G1 X95.543 Y123.343 E2.18777
G1 X94.894 Y123.343 E.02425
M73 P92 R0
G1 X54.157 Y82.606 E2.15348
G1 X54.157 Y83.255 E.02425
G1 X94.245 Y123.343 E2.11919
G1 X93.597 Y123.343 E.02425
G1 X54.157 Y83.903 E2.08489
M73 P92 R0
G1 X54.157 Y84.552 E.02425
G1 X92.948 Y123.343 E2.0506
G1 X92.299 Y123.343 E.02425
G1 X54.157 Y85.201 E2.01631
G1 X54.157 Y85.85 E.02425
G1 X91.65 Y123.343 E1.98201
G1 X91.002 Y123.343 E.02425
G1 X54.157 Y86.498 E1.94772
G1 X54.157 Y87.147 E.02425
M73 P93 R0
G1 X90.353 Y123.343 E1.91343
G1 X89.704 Y123.343 E.02425
G1 X54.157 Y87.796 E1.87913
G1 X54.157 Y88.444 E.02425
G1 X89.056 Y123.343 E1.84484
M73 P93 R0
G1 X88.407 Y123.343 E.02425
G1 X54.157 Y89.093 E1.81054
G1 X54.157 Y89.742 E.02425
G1 X87.758 Y123.343 E1.77625
G1 X87.109 Y123.343 E.02425
G1 X54.157 Y90.391 E1.74196
G1 X54.157 Y91.039 E.02425
G1 X86.461 Y123.343 E1.70766
G1 X85.812 Y123.343 E.02425
G1 X54.157 Y91.688 E1.67337
G1 X54.157 Y92.337 E.02425
M73 P94 R0
G1 X85.163 Y123.343 E1.63908
G1 X84.514 Y123.343 E.02425
G1 X54.157 Y92.986 E1.60478
G1 X54.157 Y93.634 E.02425
G1 X83.866 Y123.343 E1.57049
M73 P94 R0
G1 X83.217 Y123.343 E.02425
G1 X54.157 Y94.283 E1.5362
G1 X54.157 Y94.932 E.02425
G1 X82.568 Y123.343 E1.5019
G1 X81.92 Y123.343 E.02425
G1 X54.157 Y95.58 E1.46761
G1 X54.157 Y96.229 E.02425
G1 X81.271 Y123.343 E1.43332
G1 X80.622 Y123.343 E.02425
G1 X54.157 Y96.878 E1.39902
G1 X54.157 Y97.527 E.02425
G1 X79.973 Y123.343 E1.36473
M73 P95 R0
G1 X79.325 Y123.343 E.02425
G1 X54.157 Y98.175 E1.33044
G1 X54.157 Y98.824 E.02425
G1 X78.676 Y123.343 E1.29614
G1 X78.027 Y123.343 E.02425
M73 P95 R0
G1 X54.157 Y99.473 E1.26185
G1 X54.157 Y100.122 E.02425
G1 X77.378 Y123.343 E1.22756
G1 X76.73 Y123.343 E.02425
G1 X54.157 Y100.77 E1.19326
G1 X54.157 Y101.419 E.02425
G1 X76.081 Y123.343 E1.15897
G1 X75.432 Y123.343 E.02425
G1 X54.157 Y102.068 E1.12468
G1 X54.157 Y102.716 E.02425
G1 X74.784 Y123.343 E1.09038
G1 X74.135 Y123.343 E.02425
G1 X54.157 Y103.365 E1.05609
G1 X54.157 Y104.014 E.02425
M73 P96 R0
G1 X73.486 Y123.343 E1.02179
G1 X72.837 Y123.343 E.02425
G1 X54.157 Y104.663 E.9875
G1 X54.157 Y105.311 E.02425
G1 X72.189 Y123.343 E.95321
M73 P96 R0
G1 X71.54 Y123.343 E.02425
G1 X54.157 Y105.96 E.91891
G1 X54.157 Y106.609 E.02425
G1 X70.891 Y123.343 E.88462
G1 X70.242 Y123.343 E.02425
G1 X54.157 Y107.258 E.85033
G1 X54.157 Y107.906 E.02425
G1 X69.594 Y123.343 E.81603
G1 X68.945 Y123.343 E.02425
G1 X54.157 Y108.555 E.78174
G1 X54.157 Y109.204 E.02425
G1 X68.296 Y123.343 E.74745
G1 X67.648 Y123.343 E.02425
G1 X54.157 Y109.852 E.71315
G1 X54.157 Y110.501 E.02425
G1 X66.999 Y123.343 E.67886
G1 X66.35 Y123.343 E.02425
G1 X54.157 Y111.15 E.64457
G1 X54.157 Y111.799 E.02425
M73 P97 R0
G1 X65.701 Y123.343 E.61027
G1 X65.053 Y123.343 E.02425
G1 X54.157 Y112.447 E.57598
G1 X54.157 Y113.096 E.02425
G1 X64.404 Y123.343 E.54169
M73 P97 R0
G1 X63.755 Y123.343 E.02425
G1 X54.157 Y113.745 E.50739
G1 X54.157 Y114.393 E.02425
G1 X63.107 Y123.343 E.4731
G1 X62.458 Y123.343 E.02425
G1 X54.157 Y115.042 E.43881
G1 X54.157 Y115.691 E.02425
G1 X61.809 Y123.343 E.40451
G1 X61.16 Y123.343 E.02425
G1 X54.157 Y116.34 E.37022
G1 X54.157 Y116.988 E.02425
G1 X60.512 Y123.343 E.33592
G1 X59.863 Y123.343 E.02425
G1 X54.157 Y117.637 E.30163
G1 X54.157 Y118.286 E.02425
G1 X59.214 Y123.343 E.26734
G1 X58.565 Y123.343 E.02425
G1 X54.157 Y118.935 E.23304
G1 X54.157 Y119.583 E.02425
G1 X57.917 Y123.343 E.19875
G1 X57.268 Y123.343 E.02425
G1 X54.157 Y120.232 E.16446
G1 X54.157 Y120.881 E.02425
G1 X56.619 Y123.343 E.13016
G1 X55.971 Y123.343 E.02425
G1 X54.157 Y121.529 E.09587
G1 X54.157 Y122.178 E.02425
G1 X55.322 Y123.343 E.06158
G1 X54.673 Y123.343 E.02425
G1 X53.951 Y122.621 E.03816
G1 E-.51429 F1800
;WIPE_START
G1 F6300
G1 X54.658 Y123.328 E-.28571
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
M106 P2 S0
;TYPE:Custom
M141 S0
M104 S0
M140 S0
G1 E-3 F1800
G0 Z3.2 F600
G0 X0 Y0 F12000
M73 P98 R0
G1 Z95 F600
M106 P3 S0
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 525.65
; filament used [cm3] = 1.26
; filament used [g] = 1.57
; filament cost = 0.03
; total filament used [g] = 1.57
; total filament cost = 0.03
; total layers count = 1
; estimated printing time (normal mode) = 8m 38s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 1
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 0
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_filament_colour = ""
; default_filament_profile = "Qidi Generic PLA"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @Qidi XSmart3
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = only_one_wall_top;skirt_loops;wall_loops;;thumbnails
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 1
; draft_shield = disabled
; during_print_exhaust_fan_speed = 100
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 0
; enable_overhang_speed = 1
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #C0C0C0
; extruder_offset = 0x0
; fan_cooling_layer_time = 60
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #C0C0C0
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = " "
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 14
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Qidi Generic PLA"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = " "
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = QIDI
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 2
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; idle_temperature = 0
; independent_support_layer_height = 0
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 15%
; inherits_group = ;;"Qidi X-Smart 3 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 50%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_flow = 1
; internal_bridge_speed = 50
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = zig-zag
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_end_gcode = M141 S0\nM104 S0\nM140 S0\nG1 E-3 F1800\nG0 Z{min(max_print_height, max_layer_z + 3)} F600\nG0 X0 Y0 F12000\n{if max_layer_z < max_print_height / 2}G1 Z{max_print_height / 2 + 10} F600{else}G1 Z{min(max_print_height, max_layer_z + 3)}{endif}
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 5000
; machine_max_acceleration_travel = 0,0
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 2
; machine_max_jerk_x = 9
; machine_max_jerk_y = 9
; machine_max_jerk_z = 3
; machine_max_speed_e = 30
; machine_max_speed_x = 600
; machine_max_speed_y = 600
; machine_max_speed_z = 10
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = M0
; machine_start_gcode = PRINT_START\nG28\nM141 S0\nG0 Z50 F600\nM190 S[hot_plate_temp_initial_layer]\nG28 Z\nG29; mesh bed leveling ,comment this code to close it\nG0 X0 Y0 Z50 F6000\nM191 S{overall_chamber_temperature}\nM109 S[nozzle_temperature_initial_layer]\nM106 P3 S255\nM83\nG4 P3000\nG0 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0)} Y{max((min(print_bed_max[1], first_layer_print_min[1] + 80) - 85),0)} Z5 F6000\nG0 Z[initial_layer_print_height] F600\nG1 E3 F1800\nG1 X{(min(print_bed_max[0], first_layer_print_min[0] + 80))} E{85 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1], first_layer_print_min[1] + 80) - 85),0) + 2} E{2 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0)} E{85 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1], first_layer_print_min[1] + 80) - 85),0) + 85} E{83 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0) + 2} E{2 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1], first_layer_print_min[1] + 80) - 85),0) + 3} E{82 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0) + 12} E{-10 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 E{10 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\n
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.3
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.07
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = If you want to use Orca's chamber temperature control feature, check that printer.cfg has added the following M191 macro.\nTo add it: go to Fluidd web interface--configuration, copy the following code to the top of the printer.cfg document, SAVE&RESATART  \n\n[gcode_macro M191]\ngcode:\n    {% set s = params.S|float %}\n    {% if s == 0 %}\n        # If target temperature is 0, do nothing\n        M117 Chamber heating cancelled\n    {% else %}\n        SET_HEATER_TEMPERATURE HEATER=chamber_heater TARGET={s}\n        # Orca: uncomment the following line if you want to use heat bed to assist chamber heating\n        M140 S90\n        TEMPERATURE_WAIT SENSOR=\"heater_generic chamber_heater\" MINIMUM={s-1} MAXIMUM={s+1}\n        M117 Chamber at target temperature\n    {% endif %}
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 210
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 3000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 95%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.031
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Qidi X-Smart 3 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Qidi XSmart3
; printable_area = 0x0,175x0,175x180,0x180
; printable_height = 170
; printer_model = Qidi X-Smart 3
; printer_notes = 
; printer_settings_id = Qidi X-Smart 3 0.4 nozzle - Copy
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 15%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 10
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 4
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 270
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 140x140/PNG, 48x48/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = ;TIMELAPSE_TAKE_FRAME\n
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 3
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 60
; bed_shape = 0x0,175x0,175x180,0x180
; first_layer_temperature = 210
; first_layer_height = 0.200
; CONFIG_BLOCK_END


