; HEADER_BLOCK_START
; generated by OrcaSlicer 2.2.0 on 2025-06-04 at 11:44:41
; total layer number: 1
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 240x240 1868
; iVBORw0KGgoAAAANSUhEUgAAAPAAAADwCAYAAAA+VemSAAAFQElEQVR4Ae3dPVIkRxCA0T4Qh5CFww
; k4Ai4O7jp4uNgYnIATcLRVjBTEwuzM9ExP/WRWvRfxOZKljajIVHUtLAsAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAABwzP39/a+Pj4/fu25ubv5ZgBy+H96vdv9sAeLaTdrn5+fP/cP71e
; 7fmcYQ0KGpeyzTGAK55PB+n8YL0M+Wg7uflRo6KHF4rdTQ2G5iljq4LrigoZJT1zSGhlocXtMYCmt5
; cE1jKKjn4f0+jRfgfBEOrpUaNoh2eK3UcIa1d8ymMQQVeeqaxnBCxsP7fRovMKPMB3c/KzVTGenwfm
; WlZnhZLqq25oKLYY04dU1jpjDT4TWNGcaMB3c/h5iUHN4/WalJw8E9nJWa8Bze9UxjQhr581DpTGPC
; MHW3ZxrTlcN7fd5T05yDWz4rNU04vPWyUlPN6O+Yo+SCi+JM3faZxhTh8PbLBRebObhxslJzEYc3Xl
; ZqVtX6xWEqkwsujjJ182Qa84PPQ/kyjTF1B8g0npTDO04+N03EwR33EFupB+fwjp+VekDeMc+VaTwQ
; U3feTOPkHF654ErIwdV+VuokHF4dy0odmIsqnZMLroBMXV2aaRyEw6utmcYdObgqlUPcmMOr0vnc1I
; CDq5pZqStyeNUqF1yF+Tyk1pnGBZi66p1pvJHDqyi54LqAg6uoWalXOLyKnpX6AO+YlSkXXN+Yusra
; 9NPY4VX2ppzGDq5Ga5pD7PBq1IZeqf3iMM3QkCu1qavZGmYa+zykWUs9jU1d6f/STWOHV/pZivfUDq
; 50urArtcMrnVeoldo7ZunyQlxwmbrSdXWbxg6vVKamF1wOrlSn6iu1wyvVrcpK7R2z1K6iF1ymrtSn
; q6exwyv1bdM0dnClWF08jd/f31P9B0qj9vLy8nvZ4unp6TPTf6g0Wlf/f/Bu/zaNpba9vb2V/S5sGk
; tt2rwyr7m7u3O5JVWsydtoK7VUtmpT9xgrtVSmbn8jyQWXtL3dRdUSgWksXdbj42Osn5G1u+AyjaX1
; Qv+UytfX11R/mFKrml9UbfXw8PCZ6Q9Wql26nw3tgktKNHWPccGlWQt3UbWVCy7N1O7z0O3t7a9lNK
; axRi/9yrzGe2qN2tC/4HuflVqjNPzUPcZKrexNNXUP8blJGSv+F+6zM42VpWE+D5Xmc5OiN/3KfA6H
; WNGa9qJqKyu1omTqbuSCSz0zdQsxjdU6F1WFueBSq4Z8xxyFaaxaWZkb8QMDVDoXVR1YqXVtpm5nVm
; ptzdQNwucmXZJ3zEGZxlrL56Hg/MAAHcvKnIiVWl+5qErKSi1TNzkXXHMW5heHUYZpPE8uqgblPfX4
; WZknYBqPl4uqyXhPPU6m7qRccOXO1OU/Vup8uajiB9M4R94xc5JpHDcrM2fxnjpeLqq4mJW6f6YuV7
; FS98vUpQgXXG1zUUUVpnH9fB6iKu+p62VlphmHuFwuqujCe+rrM3XpygXXtkxdQnHBdX4uqgjJBdd6
; fnEY4ZnGf2dlJhXvqf/kooq0Zl6pTV2GMONKbeoylFk+N3nHzNBGnsY+DzGFES+4rMxMZ4SV2kUVU8
; u8Upu6sOS74PKLw+CADNPYRRWcEPk9tXfMcKZI09hFFWwQ4QcGuKiCK/VYqU1dKKjlSm3qQgW1Pzd5
; xwwN1JjGVmZoqOR7aiszdHLNSm3qQgBbVmpTFwI594LLO2YI7NQ09o4ZEjj0ntrKDMnsDrGLKgAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFj1L3Bw5na34ScOAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 96x96 756
; iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAB/klEQVR4Ae2czW2DQBCFtyAXkTZogw
; vXXLjRAwcqoAKX5miVWFkhzM/+zux+n/SkKDceM/PWY7AxAAAAAAAAAAAAAABwxOPx+LIykJ+u677X
; dX1Z2b8N5MM1/61xHJ90Q2L2jN+Km5CIK+a73WAgDneMZyRFxtd8VwS0J7aCQ82nGzyIUfV0gycpzS
; egD8hh/FaMpD9KmM9IMr97nJhBGzKSmuuGklXffDdINN/tBlMrko3fqrqRpMn8qkaSrSRNpm+lOqA1
; Vn013SDheNlkN9RU9eq6oQXz3W4wUmjJ+K2Kj6SWzX+ryEiSsseRoqwBTdV/VvJuwPxzJQlojL+vaC
; MJ8/0VNJK073GkyCugqfr4utwNmJ9Oh92A8fm0exPsP5dlUXUhWnU4joZheGq6mGqM33aDpgurynz3
; JrDvCdc0TS8TAuHsr2i7IQL6nuZ5TvNdAQF9ruQbUQK6oPkuBPS/+r4v8x0xAS3gKYlWAzpZ0PrSUk
; CLfTaohW5Q8ZhijQFdLGh94eFcAWjfJwXvcaTACxoC0BTQVb81Kfm42sybkhL3SU2+tC0hoNUdL2PD
; TxUIIHdAi9vjSCFHQFP1J6QMaMy/QcyAbj5ofeFH+wTgu0+yQWsgHncCmqpPxJXjKuZnYK8bMD4z7n
; EV8wvBp1kAAAAAAAAAAAAAgEv8AEKg0vvlB1mPAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=152.5,152.5 POLYGON=[[117.5,117.5],[187.5,117.5],[187.5,187.5],[117.5,187.5],[117.5,117.5]]
M73 P0 R4
M106 S0
M106 P2 S0
;TYPE:Custom
PRINT_START BED=60 HOTEND=210 CHAMBER=0
SET_PRINT_STATS_INFO TOTAL_LAYER=1
M83
M140 S60
M104 S210
M141 S0
G4 P3000
G0 X105.929 Y105.929 Z5 F6000
G0 Z0.2 F600
G1 E3 F1800
G1 X190.929 E3.4 F3000
G1 Y107.929 E0.08 F3000
M73 P1 R4
G1 X105.929 E3.4 F3000
M73 P1 R4
G1 Y190.929 E3.32 F3000
M73 P2 R3
G1 X107.929 E0.08 F3000
M73 P2 R3
G1 Y108.929 E3.28 F3000
G1 X108.929 Z0
M73 P3 R3
G1 X111.929
M73 P3 R3
G1 Z1 F600
SET_PRINT_STATS_INFO CURRENT_LAYER=1
M106 P3 S255
G90
G21
M83 ; use relative distances for extrusion
SET_PRESSURE_ADVANCE ADVANCE=0.034; Override pressure advance value
M106 S0
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.8 F1800
;TIMELAPSE_TAKE_FRAME

G92 E0
SET_PRINT_STATS_INFO CURRENT_LAYER=1
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500 ACCEL_TO_DECEL=250
G1 X112.846 Y113.238 F15000
G1 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Skirt
;WIDTH:0.5
G1 F3000
G1 X114.438 Y111.946 E.07635
G1 X117.5 Y111.158 E.11778
G1 X187.5 Y111.158 E2.60723
G1 X189.708 Y111.555 E.08357
M73 P4 R3
G1 X191.64 Y112.695 E.08357
M73 P4 R3
G1 X193.054 Y114.438 E.08357
G1 X193.842 Y117.5 E.11778
G1 X193.842 Y187.5 E2.60723
G1 X193.445 Y189.708 E.08357
M73 P5 R3
G1 X192.305 Y191.64 E.08357
M73 P5 R3
G1 X190.562 Y193.054 E.08357
G1 X187.5 Y193.842 E.11778
G1 X117.5 Y193.842 E2.60723
G1 X115.292 Y193.445 E.08357
G1 X113.36 Y192.305 E.08357
G1 X111.946 Y190.562 E.08357
G1 X111.158 Y187.5 E.11778
G1 X111.158 Y117.5 E2.60723
G1 X111.555 Y115.292 E.08357
M73 P6 R3
G1 X112.695 Y113.36 E.08357
M73 P6 R3
G1 X112.815 Y113.263 E.00572
G1 X113.148 Y113.539 F15000
G1 F3000
G1 X114.871 Y112.235 E.08047
G1 X117.5 Y111.615 E.10062
G1 X187.5 Y111.615 E2.60723
G1 X189.624 Y112.011 E.08047
M73 P7 R3
G1 X191.461 Y113.148 E.08047
M73 P7 R3
G1 X192.765 Y114.871 E.08047
G1 X193.385 Y117.5 E.10062
G1 X193.385 Y187.5 E2.60723
G1 X192.989 Y189.624 E.08047
G1 X191.852 Y191.461 E.08047
G1 X190.129 Y192.765 E.08047
G1 X187.5 Y193.385 E.10062
M73 P8 R3
G1 X117.5 Y193.385 E2.60723
M73 P8 R3
G1 X115.376 Y192.989 E.08047
G1 X113.539 Y191.852 E.08047
G1 X112.235 Y190.129 E.08047
G1 X111.615 Y187.5 E.10062
G1 X111.615 Y117.5 E2.60723
G1 X112.011 Y115.376 E.08047
M73 P9 R3
G1 X113.127 Y113.573 E.07898
M73 P9 R3
G1 X113.529 Y113.834 F15000
G1 F3000
G1 X113.599 Y113.725 E.00483
G1 X115.3 Y112.538 E.07726
G1 X117.5 Y112.072 E.08376
G1 X187.5 Y112.072 E2.60723
G1 X189.536 Y112.468 E.07726
G1 X191.275 Y113.599 E.07726
M73 P10 R3
G1 X192.462 Y115.3 E.07726
M73 P10 R3
G1 X192.928 Y117.5 E.08376
G1 X192.928 Y187.5 E2.60723
G1 X192.532 Y189.536 E.07726
G1 X191.401 Y191.275 E.07726
G1 X189.7 Y192.462 E.07726
G1 X187.5 Y192.928 E.08376
G1 X117.5 Y192.928 E2.60723
G1 X115.464 Y192.532 E.07726
M73 P11 R3
G1 X113.725 Y191.401 E.07726
M73 P11 R3
G1 X112.538 Y189.7 E.07726
G1 X112.072 Y187.5 E.08376
G1 X112.072 Y117.5 E2.60723
G1 X112.468 Y115.464 E.07726
G1 X113.507 Y113.867 E.07094
M73 P12 R3
G1 X113.9 Y114.138 F15000
M73 P12 R3
G1 F3000
G1 X114.05 Y113.921 E.00981
G1 X115.724 Y112.857 E.0739
G1 X117.5 Y112.529 E.06726
G1 X187.5 Y112.529 E2.60723
G1 X189.444 Y112.925 E.0739
G1 X191.079 Y114.05 E.0739
G1 X192.143 Y115.724 E.0739
G1 X192.471 Y117.5 E.06726
G1 X192.471 Y187.5 E2.60723
G1 X192.075 Y189.444 E.0739
M73 P13 R3
G1 X190.95 Y191.079 E.0739
M73 P13 R3
G1 X189.276 Y192.143 E.0739
G1 X187.5 Y192.471 E.06726
G1 X117.5 Y192.471 E2.60723
G1 X115.556 Y192.075 E.0739
M73 P14 R3
G1 X113.921 Y190.95 E.0739
M73 P14 R3
G1 X112.857 Y189.276 E.0739
G1 X112.529 Y187.5 E.06726
G1 X112.529 Y117.5 E2.60723
G1 X112.925 Y115.556 E.0739
G1 X113.878 Y114.171 E.0626
G1 X114.261 Y114.452 F15000
G1 F3000
G1 X114.499 Y114.128 E.01498
G1 X116.142 Y113.195 E.07039
G1 X117.5 Y112.986 E.05116
G1 X187.5 Y112.986 E2.60723
G1 X189.348 Y113.382 E.07039
M73 P15 R3
G1 X190.872 Y114.499 E.07039
M73 P15 R3
G1 X191.805 Y116.142 E.07039
G1 X192.014 Y117.5 E.05116
G1 X192.014 Y187.5 E2.60723
G1 X191.618 Y189.348 E.07039
M73 P16 R3
G1 X190.501 Y190.872 E.07039
M73 P16 R3
G1 X188.858 Y191.805 E.07039
G1 X187.5 Y192.014 E.05116
G1 X117.5 Y192.014 E2.60723
G1 X115.652 Y191.618 E.07039
G1 X114.128 Y190.501 E.07039
G1 X113.195 Y188.858 E.07039
G1 X112.986 Y187.5 E.05116
G1 X112.986 Y117.5 E2.60723
G1 X113.382 Y115.652 E.07039
M73 P17 R3
G1 X114.238 Y114.485 E.05392
M73 P17 R3
G1 X114.608 Y114.777 F15000
G1 F3000
G1 X114.946 Y114.348 E.02036
G1 X116.552 Y113.555 E.06669
G1 X117.5 Y113.443 E.03555
G1 X187.5 Y113.443 E2.60723
G1 X189.246 Y113.838 E.06669
M73 P18 R3
G1 X190.652 Y114.946 E.06669
M73 P18 R3
G1 X191.445 Y116.552 E.06669
G1 X191.557 Y117.5 E.03555
G1 X191.557 Y187.5 E2.60723
G1 X191.162 Y189.246 E.06669
G1 X190.054 Y190.652 E.06669
G1 X188.448 Y191.445 E.06669
G1 X187.5 Y191.557 E.03555
G1 X117.5 Y191.557 E2.60723
G1 X115.754 Y191.162 E.06669
M73 P19 R3
G1 X114.348 Y190.054 E.06669
M73 P19 R3
G1 X113.555 Y188.448 E.06669
G1 X113.443 Y187.5 E.03555
G1 X113.443 Y117.5 E2.60723
G1 X113.838 Y115.754 E.06669
G1 X114.583 Y114.808 E.04484
M73 P20 R3
G1 X114.938 Y115.112 F15000
M73 P20 R3
G1 F3000
G1 X115.392 Y114.582 E.02598
G1 X117.5 Y113.9 E.08254
G1 X187.5 Y113.9 E2.60723
G1 X189.138 Y114.295 E.06277
G1 X190.418 Y115.392 E.06277
G1 X191.1 Y117.5 E.08254
G1 X191.1 Y187.5 E2.60723
G1 X190.705 Y189.138 E.06277
M73 P21 R3
G1 X189.608 Y190.418 E.06277
M73 P21 R3
G1 X187.5 Y191.1 E.08254
G1 X117.5 Y191.1 E2.60723
G1 X115.862 Y190.705 E.06277
G1 X114.582 Y189.608 E.06277
G1 X113.9 Y187.5 E.08254
M73 P22 R3
G1 X113.9 Y117.5 E2.60723
M73 P22 R3
G1 X114.295 Y115.862 E.06277
G1 X114.911 Y115.142 E.0353
G1 X115.244 Y115.457 F15000
G1 F3000
G1 X115.833 Y114.836 E.03191
G1 X117.5 Y114.357 E.06459
G1 X187.5 Y114.357 E2.60723
G1 X189.023 Y114.751 E.05859
M73 P23 R3
G1 X190.164 Y115.833 E.05859
M73 P23 R3
G1 X190.643 Y117.5 E.06459
G1 X190.643 Y187.5 E2.60723
G1 X190.249 Y189.023 E.05859
G1 X189.167 Y190.164 E.05859
G1 X187.5 Y190.643 E.06459
G1 X117.5 Y190.643 E2.60723
M73 P24 R3
G1 X115.977 Y190.249 E.05859
M73 P24 R3
G1 X114.836 Y189.167 E.05859
G1 X114.357 Y187.5 E.06459
G1 X114.357 Y117.5 E2.60723
G1 X114.751 Y115.977 E.05859
M73 P25 R3
G1 X115.216 Y115.486 E.02519
M73 P25 R3
G1 X115.519 Y115.812 F15000
G1 F3000
G1 X116.27 Y115.113 E.03821
G1 X117.5 Y114.814 E.04715
G1 X187.5 Y114.814 E2.60723
G1 X188.898 Y115.207 E.05408
G1 X189.887 Y116.27 E.05408
G1 X190.186 Y117.5 E.04715
G1 X190.186 Y187.5 E2.60723
G1 X189.793 Y188.898 E.05408
M73 P26 R2
G1 X188.73 Y189.887 E.05408
M73 P26 R2
G1 X187.5 Y190.186 E.04715
G1 X117.5 Y190.186 E2.60723
G1 X116.102 Y189.793 E.05408
M73 P27 R2
G1 X115.113 Y188.73 E.05408
M73 P27 R2
G1 X114.814 Y187.5 E.04715
G1 X114.814 Y117.5 E2.60723
G1 X115.207 Y116.102 E.05408
G1 X115.49 Y115.839 E.01439
G1 X115.751 Y116.169 F15000
G1 F3000
G1 X116.698 Y115.421 E.04498
G1 X117.5 Y115.271 E.03037
G1 X187.5 Y115.271 E2.60723
G1 X188.761 Y115.662 E.04917
M73 P28 R2
G1 X189.579 Y116.698 E.04917
M73 P28 R2
G1 X189.729 Y117.5 E.03037
G1 X189.729 Y187.5 E2.60723
G1 X189.338 Y188.761 E.04917
M73 P29 R2
G1 X188.302 Y189.579 E.04917
M73 P29 R2
G1 X187.5 Y189.729 E.03037
G1 X117.5 Y189.729 E2.60723
G1 X116.239 Y189.338 E.04917
G1 X115.421 Y188.302 E.04917
G1 X115.271 Y187.5 E.03037
G1 X115.271 Y117.5 E2.60723
G1 X115.662 Y116.239 E.04917
M73 P30 R2
G1 X115.719 Y116.194 E.0027
;WIPE_START
M73 P30 R2
G1 X116.698 Y115.421 E-.49904
G1 X117.438 Y115.283 E-.30096
;WIPE_END
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 X122.751 Y120.763 Z.6 F15000
G1 X186.186 Y186.186 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Inner wall
G1 F3000
G1 X118.814 Y186.186 E2.50934
G1 X118.814 Y118.814 E2.50934
M73 P31 R2
G1 X186.186 Y118.814 E2.50934
M73 P32 R2
M73 P31 R2
G1 X186.186 Y186.126 E2.5071
M73 P32 R2
G1 X186.643 Y186.643 F15000
M73 P33 R2
G1 F3000
M73 P33 R2
G1 X118.357 Y186.643 E2.54339
G1 X118.357 Y118.357 E2.54339
G1 X186.643 Y118.357 E2.54339
M73 P34 R2
G1 X186.643 Y186.583 E2.54115
M73 P34 R2
G1 X187.1 Y187.1 F15000
M73 P35 R2
;TYPE:Outer wall
G1 F3000
M73 P35 R2
G1 X117.9 Y187.1 E2.57744
G1 X117.9 Y117.9 E2.57744
M73 P36 R2
G1 X187.1 Y117.9 E2.57744
M73 P36 R2
G1 X187.1 Y187.04 E2.5752
M73 P37 R2
;WIPE_START
G1 X185.1 Y187.042 E-.8
;WIPE_END
M73 P37 R2
G1 X185.208 Y179.41 Z.6 F15000
G1 X186.049 Y119.879 Z.6
M73 P38 R2
G1 Z.2
M73 P38 R2
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.501638
G1 F6300
G1 X185.327 Y119.157 E.03815
G1 X184.678 Y119.157 E.02425
G1 X185.843 Y120.322 E.06157
G1 X185.843 Y120.97 E.02425
G1 X184.03 Y119.157 E.09587
G1 X183.381 Y119.157 E.02425
G1 X185.843 Y121.619 E.13016
G1 X185.843 Y122.268 E.02425
G1 X182.732 Y119.157 E.16446
G1 X182.083 Y119.157 E.02425
G1 X185.843 Y122.917 E.19875
G1 X185.843 Y123.565 E.02425
G1 X181.435 Y119.157 E.23304
G1 X180.786 Y119.157 E.02425
G1 X185.843 Y124.214 E.26734
G1 X185.843 Y124.863 E.02425
G1 X180.137 Y119.157 E.30163
G1 X179.488 Y119.157 E.02425
G1 X185.843 Y125.512 E.33592
M73 P39 R2
G1 X185.843 Y126.16 E.02425
M73 P39 R2
G1 X178.84 Y119.157 E.37022
G1 X178.191 Y119.157 E.02425
G1 X185.843 Y126.809 E.40451
G1 X185.843 Y127.458 E.02425
G1 X177.542 Y119.157 E.4388
G1 X176.894 Y119.157 E.02425
G1 X185.843 Y128.106 E.4731
G1 X185.843 Y128.755 E.02425
G1 X176.245 Y119.157 E.50739
G1 X175.596 Y119.157 E.02425
G1 X185.843 Y129.404 E.54168
G1 X185.843 Y130.053 E.02425
G1 X174.947 Y119.157 E.57598
G1 X174.299 Y119.157 E.02425
M73 P40 R2
G1 X185.843 Y130.701 E.61027
M73 P40 R2
G1 X185.843 Y131.35 E.02425
G1 X173.65 Y119.157 E.64456
G1 X173.001 Y119.157 E.02425
G1 X185.843 Y131.999 E.67886
G1 X185.843 Y132.648 E.02425
G1 X172.352 Y119.157 E.71315
G1 X171.704 Y119.157 E.02425
G1 X185.843 Y133.296 E.74744
G1 X185.843 Y133.945 E.02425
G1 X171.055 Y119.157 E.78174
G1 X170.406 Y119.157 E.02425
G1 X185.843 Y134.594 E.81603
G1 X185.843 Y135.242 E.02425
M73 P41 R2
G1 X169.758 Y119.157 E.85033
M73 P41 R2
G1 X169.109 Y119.157 E.02425
G1 X185.843 Y135.891 E.88462
G1 X185.843 Y136.54 E.02425
G1 X168.46 Y119.157 E.91891
G1 X167.811 Y119.157 E.02425
G1 X185.843 Y137.189 E.95321
G1 X185.843 Y137.837 E.02425
G1 X167.163 Y119.157 E.9875
G1 X166.514 Y119.157 E.02425
M73 P42 R2
G1 X185.843 Y138.486 E1.02179
M73 P42 R2
G1 X185.843 Y139.135 E.02425
G1 X165.865 Y119.157 E1.05609
G1 X165.216 Y119.157 E.02425
G1 X185.843 Y139.784 E1.09038
G1 X185.843 Y140.432 E.02425
G1 X164.568 Y119.157 E1.12467
G1 X163.919 Y119.157 E.02425
G1 X185.843 Y141.081 E1.15897
G1 X185.843 Y141.73 E.02425
M73 P43 R2
G1 X163.27 Y119.157 E1.19326
M73 P43 R2
G1 X162.622 Y119.157 E.02425
G1 X185.843 Y142.378 E1.22755
G1 X185.843 Y143.027 E.02425
G1 X161.973 Y119.157 E1.26185
G1 X161.324 Y119.157 E.02425
G1 X185.843 Y143.676 E1.29614
G1 X185.843 Y144.325 E.02425
G1 X160.675 Y119.157 E1.33043
G1 X160.027 Y119.157 E.02425
M73 P44 R2
G1 X185.843 Y144.973 E1.36473
M73 P44 R2
G1 X185.843 Y145.622 E.02425
G1 X159.378 Y119.157 E1.39902
G1 X158.729 Y119.157 E.02425
G1 X185.843 Y146.271 E1.43331
G1 X185.843 Y146.92 E.02425
G1 X158.08 Y119.157 E1.46761
G1 X157.432 Y119.157 E.02425
M73 P45 R2
G1 X185.843 Y147.568 E1.5019
M73 P45 R2
G1 X185.843 Y148.217 E.02425
G1 X156.783 Y119.157 E1.53619
G1 X156.134 Y119.157 E.02425
G1 X185.843 Y148.866 E1.57049
G1 X185.843 Y149.514 E.02425
G1 X155.486 Y119.157 E1.60478
G1 X154.837 Y119.157 E.02425
M73 P46 R2
G1 X185.843 Y150.163 E1.63908
M73 P46 R2
G1 X185.843 Y150.812 E.02425
G1 X154.188 Y119.157 E1.67337
G1 X153.539 Y119.157 E.02425
G1 X185.843 Y151.461 E1.70766
G1 X185.843 Y152.109 E.02425
G1 X152.891 Y119.157 E1.74196
G1 X152.242 Y119.157 E.02425
M73 P47 R2
G1 X185.843 Y152.758 E1.77625
M73 P47 R2
G1 X185.843 Y153.407 E.02425
G1 X151.593 Y119.157 E1.81054
G1 X150.945 Y119.157 E.02425
G1 X185.843 Y154.055 E1.84484
G1 X185.843 Y154.704 E.02425
G1 X150.296 Y119.157 E1.87913
G1 X149.647 Y119.157 E.02425
M73 P48 R2
G1 X185.843 Y155.353 E1.91342
M73 P48 R2
G1 X185.843 Y156.002 E.02425
G1 X148.998 Y119.157 E1.94772
G1 X148.35 Y119.157 E.02425
G1 X185.843 Y156.65 E1.98201
G1 X185.843 Y157.299 E.02425
M73 P49 R2
G1 X147.701 Y119.157 E2.0163
M73 P49 R2
G1 X147.052 Y119.157 E.02425
G1 X185.843 Y157.948 E2.0506
G1 X185.843 Y158.597 E.02425
G1 X146.403 Y119.157 E2.08489
G1 X145.755 Y119.157 E.02425
G1 X185.843 Y159.245 E2.11918
G1 X185.843 Y159.894 E.02425
M73 P50 R2
G1 X145.106 Y119.157 E2.15348
M73 P50 R2
G1 X144.457 Y119.157 E.02425
G1 X185.843 Y160.543 E2.18777
G1 X185.843 Y161.191 E.02425
G1 X143.809 Y119.157 E2.22206
G1 X143.16 Y119.157 E.02425
M73 P51 R1
G1 X185.843 Y161.84 E2.25636
M73 P51 R1
G1 X185.843 Y162.489 E.02425
G1 X142.511 Y119.157 E2.29065
G1 X141.862 Y119.157 E.02425
G1 X185.843 Y163.138 E2.32494
G1 X185.843 Y163.786 E.02425
M73 P52 R1
G1 X141.214 Y119.157 E2.35924
M73 P52 R1
G1 X140.565 Y119.157 E.02425
G1 X185.843 Y164.435 E2.39353
G1 X185.843 Y165.084 E.02425
G1 X139.916 Y119.157 E2.42783
G1 X139.267 Y119.157 E.02425
M73 P53 R1
G1 X185.843 Y165.733 E2.46212
M73 P53 R1
G1 X185.843 Y166.381 E.02425
G1 X138.619 Y119.157 E2.49641
G1 X137.97 Y119.157 E.02425
G1 X185.843 Y167.03 E2.53071
G1 X185.843 Y167.679 E.02425
M73 P54 R1
G1 X137.321 Y119.157 E2.565
M73 P54 R1
G1 X136.673 Y119.157 E.02425
G1 X185.843 Y168.327 E2.59929
G1 X185.843 Y168.976 E.02425
G1 X136.024 Y119.157 E2.63359
G1 X135.375 Y119.157 E.02425
M73 P55 R1
G1 X185.843 Y169.625 E2.66788
M73 P55 R1
G1 X185.843 Y170.274 E.02425
G1 X134.726 Y119.157 E2.70217
G1 X134.078 Y119.157 E.02425
M73 P56 R1
G1 X185.843 Y170.922 E2.73647
M73 P56 R1
G1 X185.843 Y171.571 E.02425
G1 X133.429 Y119.157 E2.77076
G1 X132.78 Y119.157 E.02425
G1 X185.843 Y172.22 E2.80505
G1 X185.843 Y172.869 E.02425
M73 P57 R1
G1 X132.131 Y119.157 E2.83935
M73 P57 R1
G1 X131.483 Y119.157 E.02425
G1 X185.843 Y173.517 E2.87364
G1 X185.843 Y174.166 E.02425
G1 X130.834 Y119.157 E2.90793
G1 X130.185 Y119.157 E.02425
M73 P58 R1
G1 X185.843 Y174.815 E2.94223
M73 P58 R1
G1 X185.843 Y175.463 E.02425
G1 X129.537 Y119.157 E2.97652
G1 X128.888 Y119.157 E.02425
M73 P59 R1
G1 X185.843 Y176.112 E3.01081
M73 P59 R1
G1 X185.843 Y176.761 E.02425
G1 X128.239 Y119.157 E3.04511
G1 X127.59 Y119.157 E.02425
G1 X185.843 Y177.41 E3.0794
G1 X185.843 Y178.058 E.02425
M73 P60 R1
G1 X126.942 Y119.157 E3.1137
M73 P60 R1
G1 X126.293 Y119.157 E.02425
G1 X185.843 Y178.707 E3.14799
G1 X185.843 Y179.356 E.02425
M73 P61 R1
G1 X125.644 Y119.157 E3.18228
M73 P61 R1
G1 X124.996 Y119.157 E.02425
G1 X185.843 Y180.004 E3.21658
G1 X185.843 Y180.653 E.02425
G1 X124.347 Y119.157 E3.25087
M73 P62 R1
G1 X123.698 Y119.157 E.02425
M73 P62 R1
G1 X185.843 Y181.302 E3.28516
G1 X185.843 Y181.951 E.02425
G1 X123.049 Y119.157 E3.31946
G1 X122.401 Y119.157 E.02425
M73 P63 R1
G1 X185.843 Y182.599 E3.35375
M73 P63 R1
G1 X185.843 Y183.248 E.02425
G1 X121.752 Y119.157 E3.38804
G1 X121.103 Y119.157 E.02425
M73 P64 R1
G1 X185.843 Y183.897 E3.42234
M73 P64 R1
G1 X185.843 Y184.546 E.02425
G1 X120.454 Y119.157 E3.45663
G1 X119.806 Y119.157 E.02425
M73 P65 R1
G1 X185.843 Y185.194 E3.49092
M73 P65 R1
G1 X185.843 Y185.843 E.02425
G1 X119.157 Y119.157 E3.52522
G1 X119.157 Y119.806 E.02425
G1 X185.194 Y185.843 E3.49093
G1 X184.546 Y185.843 E.02425
M73 P66 R1
G1 X119.157 Y120.454 E3.45663
M73 P66 R1
G1 X119.157 Y121.103 E.02425
G1 X183.897 Y185.843 E3.42234
G1 X183.248 Y185.843 E.02425
M73 P67 R1
G1 X119.157 Y121.752 E3.38805
M73 P67 R1
G1 X119.157 Y122.401 E.02425
G1 X182.599 Y185.843 E3.35375
G1 X181.951 Y185.843 E.02425
M73 P68 R1
G1 X119.157 Y123.049 E3.31946
M73 P68 R1
G1 X119.157 Y123.698 E.02425
G1 X181.302 Y185.843 E3.28516
G1 X180.653 Y185.843 E.02425
M73 P69 R1
G1 X119.157 Y124.347 E3.25087
M73 P69 R1
G1 X119.157 Y124.995 E.02425
G1 X180.005 Y185.843 E3.21658
G1 X179.356 Y185.843 E.02425
G1 X119.157 Y125.644 E3.18228
G1 X119.157 Y126.293 E.02425
M73 P70 R1
G1 X178.707 Y185.843 E3.14799
M73 P70 R1
G1 X178.058 Y185.843 E.02425
G1 X119.157 Y126.942 E3.1137
G1 X119.157 Y127.59 E.02425
M73 P71 R1
G1 X177.41 Y185.843 E3.0794
M73 P71 R1
G1 X176.761 Y185.843 E.02425
G1 X119.157 Y128.239 E3.04511
G1 X119.157 Y128.888 E.02425
G1 X176.112 Y185.843 E3.01082
G1 X175.463 Y185.843 E.02425
M73 P72 R1
G1 X119.157 Y129.537 E2.97652
M73 P72 R1
G1 X119.157 Y130.185 E.02425
G1 X174.815 Y185.843 E2.94223
G1 X174.166 Y185.843 E.02425
M73 P73 R1
G1 X119.157 Y130.834 E2.90794
M73 P73 R1
G1 X119.157 Y131.483 E.02425
G1 X173.517 Y185.843 E2.87364
G1 X172.869 Y185.843 E.02425
G1 X119.157 Y132.131 E2.83935
G1 X119.157 Y132.78 E.02425
M73 P74 R1
G1 X172.22 Y185.843 E2.80506
M73 P74 R1
G1 X171.571 Y185.843 E.02425
G1 X119.157 Y133.429 E2.77076
G1 X119.157 Y134.078 E.02425
M73 P75 R1
G1 X170.922 Y185.843 E2.73647
M73 P75 R1
G1 X170.274 Y185.843 E.02425
G1 X119.157 Y134.726 E2.70218
G1 X119.157 Y135.375 E.02425
M73 P75 R0
G1 X169.625 Y185.843 E2.66788
M73 P75 R0
G1 X168.976 Y185.843 E.02425
M73 P76 R0
G1 X119.157 Y136.024 E2.63359
M73 P76 R0
G1 X119.157 Y136.673 E.02425
G1 X168.327 Y185.843 E2.59929
G1 X167.679 Y185.843 E.02425
G1 X119.157 Y137.321 E2.565
G1 X119.157 Y137.97 E.02425
M73 P77 R0
G1 X167.03 Y185.843 E2.53071
M73 P77 R0
G1 X166.381 Y185.843 E.02425
G1 X119.157 Y138.619 E2.49641
G1 X119.157 Y139.267 E.02425
G1 X165.733 Y185.843 E2.46212
G1 X165.084 Y185.843 E.02425
M73 P78 R0
G1 X119.157 Y139.916 E2.42783
M73 P78 R0
G1 X119.157 Y140.565 E.02425
G1 X164.435 Y185.843 E2.39353
G1 X163.786 Y185.843 E.02425
G1 X119.157 Y141.214 E2.35924
G1 X119.157 Y141.862 E.02425
M73 P79 R0
G1 X163.138 Y185.843 E2.32495
M73 P79 R0
G1 X162.489 Y185.843 E.02425
G1 X119.157 Y142.511 E2.29065
G1 X119.157 Y143.16 E.02425
G1 X161.84 Y185.843 E2.25636
G1 X161.191 Y185.843 E.02425
M73 P80 R0
G1 X119.157 Y143.809 E2.22207
M73 P80 R0
G1 X119.157 Y144.457 E.02425
G1 X160.543 Y185.843 E2.18777
G1 X159.894 Y185.843 E.02425
G1 X119.157 Y145.106 E2.15348
G1 X119.157 Y145.755 E.02425
M73 P81 R0
G1 X159.245 Y185.843 E2.11919
M73 P81 R0
G1 X158.597 Y185.843 E.02425
G1 X119.157 Y146.403 E2.08489
G1 X119.157 Y147.052 E.02425
G1 X157.948 Y185.843 E2.0506
G1 X157.299 Y185.843 E.02425
M73 P82 R0
G1 X119.157 Y147.701 E2.01631
M73 P82 R0
G1 X119.157 Y148.35 E.02425
G1 X156.65 Y185.843 E1.98201
G1 X156.002 Y185.843 E.02425
G1 X119.157 Y148.998 E1.94772
G1 X119.157 Y149.647 E.02425
G1 X155.353 Y185.843 E1.91343
G1 X154.704 Y185.843 E.02425
M73 P83 R0
G1 X119.157 Y150.296 E1.87913
M73 P83 R0
G1 X119.157 Y150.944 E.02425
G1 X154.056 Y185.843 E1.84484
G1 X153.407 Y185.843 E.02425
G1 X119.157 Y151.593 E1.81054
G1 X119.157 Y152.242 E.02425
M73 P84 R0
G1 X152.758 Y185.843 E1.77625
M73 P84 R0
G1 X152.109 Y185.843 E.02425
G1 X119.157 Y152.891 E1.74196
G1 X119.157 Y153.539 E.02425
G1 X151.461 Y185.843 E1.70766
G1 X150.812 Y185.843 E.02425
G1 X119.157 Y154.188 E1.67337
G1 X119.157 Y154.837 E.02425
M73 P85 R0
G1 X150.163 Y185.843 E1.63908
M73 P85 R0
G1 X149.514 Y185.843 E.02425
G1 X119.157 Y155.486 E1.60478
G1 X119.157 Y156.134 E.02425
G1 X148.866 Y185.843 E1.57049
G1 X148.217 Y185.843 E.02425
G1 X119.157 Y156.783 E1.5362
G1 X119.157 Y157.432 E.02425
M73 P86 R0
G1 X147.568 Y185.843 E1.5019
M73 P86 R0
G1 X146.92 Y185.843 E.02425
G1 X119.157 Y158.08 E1.46761
G1 X119.157 Y158.729 E.02425
G1 X146.271 Y185.843 E1.43332
G1 X145.622 Y185.843 E.02425
G1 X119.157 Y159.378 E1.39902
G1 X119.157 Y160.027 E.02425
M73 P87 R0
G1 X144.973 Y185.843 E1.36473
M73 P87 R0
G1 X144.325 Y185.843 E.02425
G1 X119.157 Y160.675 E1.33044
G1 X119.157 Y161.324 E.02425
G1 X143.676 Y185.843 E1.29614
G1 X143.027 Y185.843 E.02425
G1 X119.157 Y161.973 E1.26185
G1 X119.157 Y162.622 E.02425
G1 X142.378 Y185.843 E1.22756
M73 P88 R0
G1 X141.73 Y185.843 E.02425
M73 P88 R0
G1 X119.157 Y163.27 E1.19326
G1 X119.157 Y163.919 E.02425
G1 X141.081 Y185.843 E1.15897
G1 X140.432 Y185.843 E.02425
G1 X119.157 Y164.568 E1.12468
G1 X119.157 Y165.216 E.02425
G1 X139.784 Y185.843 E1.09038
G1 X139.135 Y185.843 E.02425
M73 P89 R0
G1 X119.157 Y165.865 E1.05609
M73 P89 R0
G1 X119.157 Y166.514 E.02425
G1 X138.486 Y185.843 E1.02179
G1 X137.837 Y185.843 E.02425
G1 X119.157 Y167.163 E.9875
G1 X119.157 Y167.811 E.02425
G1 X137.189 Y185.843 E.95321
G1 X136.54 Y185.843 E.02425
G1 X119.157 Y168.46 E.91891
G1 X119.157 Y169.109 E.02425
G1 X135.891 Y185.843 E.88462
G1 X135.242 Y185.843 E.02425
M73 P90 R0
G1 X119.157 Y169.758 E.85033
M73 P90 R0
G1 X119.157 Y170.406 E.02425
G1 X134.594 Y185.843 E.81603
G1 X133.945 Y185.843 E.02425
G1 X119.157 Y171.055 E.78174
G1 X119.157 Y171.704 E.02425
G1 X133.296 Y185.843 E.74745
G1 X132.648 Y185.843 E.02425
G1 X119.157 Y172.352 E.71315
G1 X119.157 Y173.001 E.02425
G1 X131.999 Y185.843 E.67886
M73 P91 R0
G1 X131.35 Y185.843 E.02425
M73 P91 R0
G1 X119.157 Y173.65 E.64457
G1 X119.157 Y174.299 E.02425
G1 X130.701 Y185.843 E.61027
G1 X130.053 Y185.843 E.02425
G1 X119.157 Y174.947 E.57598
G1 X119.157 Y175.596 E.02425
G1 X129.404 Y185.843 E.54169
G1 X128.755 Y185.843 E.02425
G1 X119.157 Y176.245 E.50739
G1 X119.157 Y176.893 E.02425
G1 X128.107 Y185.843 E.4731
G1 X127.458 Y185.843 E.02425
G1 X119.157 Y177.542 E.43881
M73 P92 R0
G1 X119.157 Y178.191 E.02425
M73 P92 R0
G1 X126.809 Y185.843 E.40451
G1 X126.16 Y185.843 E.02425
G1 X119.157 Y178.84 E.37022
G1 X119.157 Y179.488 E.02425
G1 X125.512 Y185.843 E.33592
G1 X124.863 Y185.843 E.02425
G1 X119.157 Y180.137 E.30163
G1 X119.157 Y180.786 E.02425
G1 X124.214 Y185.843 E.26734
G1 X123.565 Y185.843 E.02425
G1 X119.157 Y181.435 E.23304
G1 X119.157 Y182.083 E.02425
G1 X122.917 Y185.843 E.19875
G1 X122.268 Y185.843 E.02425
G1 X119.157 Y182.732 E.16446
G1 X119.157 Y183.381 E.02425
G1 X121.619 Y185.843 E.13016
G1 X120.971 Y185.843 E.02425
G1 X119.157 Y184.029 E.09587
M73 P93 R0
G1 X119.157 Y184.678 E.02425
M73 P93 R0
G1 X120.322 Y185.843 E.06158
G1 X119.673 Y185.843 E.02425
G1 X118.951 Y185.121 E.03816
G1 E-.22857 F1800
;WIPE_START
G1 F6300
G1 X119.673 Y185.843 E-.29165
G1 X120.322 Y185.843 E-.18535
G1 X120.088 Y185.609 E-.09443
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
M106 P2 S0
;TYPE:Custom
M141 S0
M104 S0
M140 S0
G1 E-3 F1800
G0 Z3.2 F600
G0 X0 Y0 F12000
G1 Z150 F600
M106 P3 S0
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 525.65
; filament used [cm3] = 1.26
; filament used [g] = 1.57
; filament cost = 0.03
; total filament used [g] = 1.57
; total filament cost = 0.03
; total layers count = 1
; estimated printing time (normal mode) = 4m 4s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 1
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x305,0x302,35x302,35x305,305x305,305x305,305x305,305x20,293x20,293x0,305x0,305x20,305x305
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 0
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_filament_colour = ""
; default_filament_profile = "Qidi Generic PLA @Qidi X-Plus 4 0.4 nozzle"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @Qidi XPlus4
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = only_one_wall_top;skirt_loops;wall_loops;;thumbnails
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 1
; draft_shield = disabled
; during_print_exhaust_fan_speed = 100
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 0
; enable_overhang_speed = 1
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 135
; extruder_clearance_height_to_rod = 32
; extruder_clearance_radius = 72
; extruder_colour = #C0C0C0
; extruder_offset = 0x0
; fan_cooling_layer_time = 60
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #C0C0C0
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = " "
; filament_flow_ratio = 0.98
; filament_ids = GFB99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 14
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Qidi Generic PLA @Qidi X-Plus 4 0.4 nozzle"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = " "
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = QIDI
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 2
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; idle_temperature = 0
; independent_support_layer_height = 0
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 15%
; inherits_group = ;;"Qidi X-Plus 4 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 50%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_flow = 1
; internal_bridge_speed = 50
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = zig-zag
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = G92 E0\nSET_PRINT_STATS_INFO CURRENT_LAYER={layer_num + 1}
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_end_gcode = M141 S0\nM104 S0\nM140 S0\nG1 E-3 F1800\nG0 Z{min(max_print_height, max_layer_z + 3)} F600\nG0 X0 Y0 F12000\n{if max_layer_z < max_print_height / 2}G1 Z{max_print_height / 2 + 10} F600{else}G1 Z{min(max_print_height, max_layer_z + 3)}{endif}
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 20000
; machine_max_acceleration_travel = 0,0
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 4
; machine_max_jerk_x = 9
; machine_max_jerk_y = 9
; machine_max_jerk_z = 4
; machine_max_speed_e = 30
; machine_max_speed_x = 600
; machine_max_speed_y = 600
; machine_max_speed_z = 20
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = M0
; machine_start_gcode = PRINT_START BED=[hot_plate_temp_initial_layer] HOTEND=[nozzle_temperature_initial_layer] CHAMBER=[chamber_temperature]\nSET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count]\nM83\nM140 S[hot_plate_temp_initial_layer]\nM104 S[nozzle_temperature_initial_layer]\nM141 S[chamber_temperature]\nG4 P3000\nG0 X{max((min(print_bed_max[0] - 12, first_layer_print_min[0] + 80) - 85), 0)} Y{max((min(print_bed_max[1] - 3, first_layer_print_min[1] + 80) - 85), 0)} Z5 F6000\nG0 Z[initial_layer_print_height] F600\nG1 E3 F1800\nG1 X{(min(print_bed_max[0] - 12, first_layer_print_min[0] + 80))} E{85 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1] - 3, first_layer_print_min[1] + 80) - 85), 0) + 2} E{2 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0] - 12, first_layer_print_min[0] + 80) - 85), 0)} E{85 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1] - 3, first_layer_print_min[1] + 80) - 85), 0) + 85} E{83 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0] - 12, first_layer_print_min[0] + 80) - 85), 0) + 2} E{2 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1] - 3, first_layer_print_min[1] + 80) - 85), 0) + 3} E{82 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0] - 12, first_layer_print_min[0] + 80) - 85), 0) + 3} Z0\nG1 X{max((min(print_bed_max[0] - 12, first_layer_print_min[0] + 80) - 85), 0) + 6}\nG1 Z1 F600\nSET_PRINT_STATS_INFO CURRENT_LAYER=1\n
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.28
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = If you want to use Orca's chamber temperature control feature, check that printer.cfg has added the following M191 macro.\nTo add it: go to Fluidd web interface--configuration, copy the following code to the top of the printer.cfg document, SAVE&RESATART  \n\n[gcode_macro M191]\ngcode:\n    {% set s = params.S|float %}\n    {% if s == 0 %}\n        # If target temperature is 0, do nothing\n        M117 Chamber heating cancelled\n    {% else %}\n        SET_HEATER_TEMPERATURE HEATER=chamber_heater TARGET={s}\n        # Orca: uncomment the following line if you want to use heat bed to assist chamber heating\n        M140 S90\n        TEMPERATURE_WAIT SENSOR=\"heater_generic chamber_heater\" MINIMUM={s-1} MAXIMUM={s+1}\n        M117 Chamber at target temperature\n    {% endif %}
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 210
; nozzle_temperature_initial_layer = 210
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 3000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 95%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.034
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Qidi X-Plus 4 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Qidi XPlus4
; printable_area = 0x0,305x0,305x305,0x305
; printable_height = 280
; printer_model = Qidi X-Plus 4
; printer_notes = 
; printer_settings_id = Qidi X-Plus 4 0.4 nozzle - Copy
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 15%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 10
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 4
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 270
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 240x240/PNG, 96x96/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = ;TIMELAPSE_TAKE_FRAME\n
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 3
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 2
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 60
; bed_shape = 0x0,305x0,305x305,0x305
; first_layer_temperature = 210
; first_layer_height = 0.200
; CONFIG_BLOCK_END


