; HEADER_BLOCK_START
; generated by OrcaSlicer 2.2.0 on 2025-06-04 at 11:46:17
; total layer number: 1
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 240x240 1868
; iVBORw0KGgoAAAANSUhEUgAAAPAAAADwCAYAAAA+VemSAAAFQElEQVR4Ae3dPVIkRxCA0T4Qh5CFww
; k4Ai4O7jp4uNgYnIATcLRVjBTEwuzM9ExP/WRWvRfxOZKljajIVHUtLAsAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAABwzP39/a+Pj4/fu25ubv5ZgBy+H96vdv9sAeLaTdrn5+fP/cP71e
; 7fmcYQ0KGpeyzTGAK55PB+n8YL0M+Wg7uflRo6KHF4rdTQ2G5iljq4LrigoZJT1zSGhlocXtMYCmt5
; cE1jKKjn4f0+jRfgfBEOrpUaNoh2eK3UcIa1d8ymMQQVeeqaxnBCxsP7fRovMKPMB3c/KzVTGenwfm
; WlZnhZLqq25oKLYY04dU1jpjDT4TWNGcaMB3c/h5iUHN4/WalJw8E9nJWa8Bze9UxjQhr581DpTGPC
; MHW3ZxrTlcN7fd5T05yDWz4rNU04vPWyUlPN6O+Yo+SCi+JM3faZxhTh8PbLBRebObhxslJzEYc3Xl
; ZqVtX6xWEqkwsujjJ182Qa84PPQ/kyjTF1B8g0npTDO04+N03EwR33EFupB+fwjp+VekDeMc+VaTwQ
; U3feTOPkHF654ErIwdV+VuokHF4dy0odmIsqnZMLroBMXV2aaRyEw6utmcYdObgqlUPcmMOr0vnc1I
; CDq5pZqStyeNUqF1yF+Tyk1pnGBZi66p1pvJHDqyi54LqAg6uoWalXOLyKnpX6AO+YlSkXXN+Yusra
; 9NPY4VX2ppzGDq5Ga5pD7PBq1IZeqf3iMM3QkCu1qavZGmYa+zykWUs9jU1d6f/STWOHV/pZivfUDq
; 50urArtcMrnVeoldo7ZunyQlxwmbrSdXWbxg6vVKamF1wOrlSn6iu1wyvVrcpK7R2z1K6iF1ymrtSn
; q6exwyv1bdM0dnClWF08jd/f31P9B0qj9vLy8nvZ4unp6TPTf6g0Wlf/f/Bu/zaNpba9vb2V/S5sGk
; tt2rwyr7m7u3O5JVWsydtoK7VUtmpT9xgrtVSmbn8jyQWXtL3dRdUSgWksXdbj42Osn5G1u+AyjaX1
; Qv+UytfX11R/mFKrml9UbfXw8PCZ6Q9Wql26nw3tgktKNHWPccGlWQt3UbWVCy7N1O7z0O3t7a9lNK
; axRi/9yrzGe2qN2tC/4HuflVqjNPzUPcZKrexNNXUP8blJGSv+F+6zM42VpWE+D5Xmc5OiN/3KfA6H
; WNGa9qJqKyu1omTqbuSCSz0zdQsxjdU6F1WFueBSq4Z8xxyFaaxaWZkb8QMDVDoXVR1YqXVtpm5nVm
; ptzdQNwucmXZJ3zEGZxlrL56Hg/MAAHcvKnIiVWl+5qErKSi1TNzkXXHMW5heHUYZpPE8uqgblPfX4
; WZknYBqPl4uqyXhPPU6m7qRccOXO1OU/Vup8uajiB9M4R94xc5JpHDcrM2fxnjpeLqq4mJW6f6YuV7
; FS98vUpQgXXG1zUUUVpnH9fB6iKu+p62VlphmHuFwuqujCe+rrM3XpygXXtkxdQnHBdX4uqgjJBdd6
; fnEY4ZnGf2dlJhXvqf/kooq0Zl6pTV2GMONKbeoylFk+N3nHzNBGnsY+DzGFES+4rMxMZ4SV2kUVU8
; u8Upu6sOS74PKLw+CADNPYRRWcEPk9tXfMcKZI09hFFWwQ4QcGuKiCK/VYqU1dKKjlSm3qQgW1Pzd5
; xwwN1JjGVmZoqOR7aiszdHLNSm3qQgBbVmpTFwI594LLO2YI7NQ09o4ZEjj0ntrKDMnsDrGLKgAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFj1L3Bw5na34ScOAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 96x96 756
; iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAB/klEQVR4Ae2czW2DQBCFtyAXkTZogw
; vXXLjRAwcqoAKX5miVWFkhzM/+zux+n/SkKDceM/PWY7AxAAAAAAAAAAAAAABwxOPx+LIykJ+u677X
; dX1Z2b8N5MM1/61xHJ90Q2L2jN+Km5CIK+a73WAgDneMZyRFxtd8VwS0J7aCQ82nGzyIUfV0gycpzS
; egD8hh/FaMpD9KmM9IMr97nJhBGzKSmuuGklXffDdINN/tBlMrko3fqrqRpMn8qkaSrSRNpm+lOqA1
; Vn013SDheNlkN9RU9eq6oQXz3W4wUmjJ+K2Kj6SWzX+ryEiSsseRoqwBTdV/VvJuwPxzJQlojL+vaC
; MJ8/0VNJK073GkyCugqfr4utwNmJ9Oh92A8fm0exPsP5dlUXUhWnU4joZheGq6mGqM33aDpgurynz3
; JrDvCdc0TS8TAuHsr2i7IQL6nuZ5TvNdAQF9ruQbUQK6oPkuBPS/+r4v8x0xAS3gKYlWAzpZ0PrSUk
; CLfTaohW5Q8ZhijQFdLGh94eFcAWjfJwXvcaTACxoC0BTQVb81Kfm42sybkhL3SU2+tC0hoNUdL2PD
; TxUIIHdAi9vjSCFHQFP1J6QMaMy/QcyAbj5ofeFH+wTgu0+yQWsgHncCmqpPxJXjKuZnYK8bMD4z7n
; EV8wvBp1kAAAAAAAAAAAAAgEv8AEKg0vvlB1mPAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=162.5,162.5 POLYGON=[[127.5,127.5],[197.5,127.5],[197.5,197.5],[127.5,197.5],[127.5,127.5]]
M73 P0 R8
M106 S0
M106 P2 S0
;TYPE:Custom
PRINT_START
G28
M141 S0
G0 Z50 F600
M190 S60
G28 Z
G29; mesh bed leveling ,comment this code to close it
G0 X0 Y0 Z50 F6000
M73 P51 R4
M191 S0
M109 S210
M106 P3 S255
M83
G4 P3000
G0 X115.929 Y115.929 Z5 F6000
M73 P52 R4
G0 Z0.2 F600
M73 P53 R4
G1 E3 F1800
G1 X200.929 E3.4 F3000
M73 P50 R4
G1 Y117.929 E0.08 F3000
M73 P51 R4
G1 X115.929 E3.4 F3000
M73 P52 R4
G1 Y200.929 E3.32 F3000
M73 P53 R4
G1 X117.929 E0.08 F3000
M73 P54 R4
G1 Y118.929 E3.28 F3000
G1 X127.929 E-0.4 F3000
G1 E0.4 F3000
M73 P54 R3
M106 P3 S255
G90
G21
M83 ; use relative distances for extrusion
SET_PRESSURE_ADVANCE ADVANCE=0.031; Override pressure advance value
M106 S0
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-1 F1800
;TIMELAPSE_TAKE_FRAME

;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500 ACCEL_TO_DECEL=250
G1 X122.846 Y123.238 F15000
M73 P54 R4
G1 Z.6
G1 Z.2
G1 E1 F1800
;TYPE:Skirt
;WIDTH:0.5
M73 P54 R3
G1 F3000
G1 X124.438 Y121.946 E.07635
G1 X127.5 Y121.158 E.11778
G1 X197.5 Y121.158 E2.60723
G1 X199.708 Y121.555 E.08357
G1 X201.64 Y122.695 E.08357
G1 X203.054 Y124.438 E.08357
G1 X203.842 Y127.5 E.11778
G1 X203.842 Y197.5 E2.60723
G1 X203.445 Y199.708 E.08357
M73 P55 R3
G1 X202.305 Y201.64 E.08357
G1 X200.562 Y203.054 E.08357
G1 X197.5 Y203.842 E.11778
G1 X127.5 Y203.842 E2.60723
G1 X125.292 Y203.445 E.08357
M73 P55 R3
G1 X123.36 Y202.305 E.08357
G1 X121.946 Y200.562 E.08357
G1 X121.158 Y197.5 E.11778
G1 X121.158 Y127.5 E2.60723
G1 X121.555 Y125.292 E.08357
G1 X122.695 Y123.36 E.08357
G1 X122.815 Y123.263 E.00572
G1 X123.148 Y123.539 F15000
G1 F3000
G1 X124.871 Y122.235 E.08047
G1 X127.5 Y121.615 E.10062
G1 X197.5 Y121.615 E2.60723
G1 X199.624 Y122.011 E.08047
M73 P56 R3
G1 X201.461 Y123.148 E.08047
G1 X202.765 Y124.871 E.08047
G1 X203.385 Y127.5 E.10062
G1 X203.385 Y197.5 E2.60723
G1 X202.989 Y199.624 E.08047
M73 P56 R3
G1 X201.852 Y201.461 E.08047
G1 X200.129 Y202.765 E.08047
G1 X197.5 Y203.385 E.10062
G1 X127.5 Y203.385 E2.60723
G1 X125.376 Y202.989 E.08047
G1 X123.539 Y201.852 E.08047
G1 X122.235 Y200.129 E.08047
G1 X121.615 Y197.5 E.10062
G1 X121.615 Y127.5 E2.60723
G1 X122.011 Y125.376 E.08047
M73 P57 R3
G1 X123.127 Y123.573 E.07898
G1 X123.529 Y123.834 F15000
G1 F3000
G1 X123.599 Y123.725 E.00483
G1 X125.3 Y122.538 E.07726
M73 P57 R3
G1 X127.5 Y122.072 E.08376
G1 X197.5 Y122.072 E2.60723
G1 X199.536 Y122.468 E.07726
G1 X201.275 Y123.599 E.07726
G1 X202.462 Y125.3 E.07726
G1 X202.928 Y127.5 E.08376
G1 X202.928 Y197.5 E2.60723
G1 X202.532 Y199.536 E.07726
G1 X201.401 Y201.275 E.07726
G1 X199.7 Y202.462 E.07726
G1 X197.5 Y202.928 E.08376
G1 X127.5 Y202.928 E2.60723
G1 X125.464 Y202.532 E.07726
M73 P58 R3
G1 X123.725 Y201.401 E.07726
G1 X122.538 Y199.7 E.07726
G1 X122.072 Y197.5 E.08376
G1 X122.072 Y127.5 E2.60723
G1 X122.468 Y125.464 E.07726
M73 P58 R3
G1 X123.507 Y123.867 E.07094
G1 X123.9 Y124.138 F15000
G1 F3000
G1 X124.05 Y123.921 E.00981
G1 X125.724 Y122.857 E.0739
G1 X127.5 Y122.529 E.06726
G1 X197.5 Y122.529 E2.60723
G1 X199.444 Y122.925 E.0739
G1 X201.079 Y124.05 E.0739
G1 X202.143 Y125.724 E.0739
G1 X202.471 Y127.5 E.06726
G1 X202.471 Y197.5 E2.60723
G1 X202.075 Y199.444 E.0739
G1 X200.95 Y201.079 E.0739
M73 P59 R3
G1 X199.276 Y202.143 E.0739
G1 X197.5 Y202.471 E.06726
G1 X127.5 Y202.471 E2.60723
G1 X125.556 Y202.075 E.0739
G1 X123.921 Y200.95 E.0739
M73 P59 R3
G1 X122.857 Y199.276 E.0739
G1 X122.529 Y197.5 E.06726
G1 X122.529 Y127.5 E2.60723
G1 X122.925 Y125.556 E.0739
G1 X123.878 Y124.171 E.0626
G1 X124.261 Y124.452 F15000
G1 F3000
G1 X124.499 Y124.128 E.01498
G1 X126.142 Y123.195 E.07039
G1 X127.5 Y122.986 E.05116
G1 X197.5 Y122.986 E2.60723
G1 X199.348 Y123.382 E.07039
G1 X200.872 Y124.499 E.07039
G1 X201.805 Y126.142 E.07039
G1 X202.014 Y127.5 E.05116
G1 X202.014 Y197.5 E2.60723
G1 X201.618 Y199.348 E.07039
M73 P60 R3
G1 X200.501 Y200.872 E.07039
G1 X198.858 Y201.805 E.07039
G1 X197.5 Y202.014 E.05116
G1 X127.5 Y202.014 E2.60723
G1 X125.652 Y201.618 E.07039
M73 P60 R3
G1 X124.128 Y200.501 E.07039
G1 X123.195 Y198.858 E.07039
G1 X122.986 Y197.5 E.05116
G1 X122.986 Y127.5 E2.60723
G1 X123.382 Y125.652 E.07039
G1 X124.238 Y124.485 E.05392
G1 X124.608 Y124.777 F15000
G1 F3000
G1 X124.946 Y124.348 E.02036
G1 X126.552 Y123.555 E.06669
G1 X127.5 Y123.443 E.03555
G1 X197.5 Y123.443 E2.60723
G1 X199.246 Y123.838 E.06669
M73 P61 R3
G1 X200.652 Y124.946 E.06669
G1 X201.445 Y126.552 E.06669
G1 X201.557 Y127.5 E.03555
G1 X201.557 Y197.5 E2.60723
G1 X201.162 Y199.246 E.06669
M73 P61 R3
G1 X200.054 Y200.652 E.06669
G1 X198.448 Y201.445 E.06669
G1 X197.5 Y201.557 E.03555
G1 X127.5 Y201.557 E2.60723
G1 X125.754 Y201.162 E.06669
G1 X124.348 Y200.054 E.06669
G1 X123.555 Y198.448 E.06669
G1 X123.443 Y197.5 E.03555
G1 X123.443 Y127.5 E2.60723
G1 X123.838 Y125.754 E.06669
M73 P62 R3
G1 X124.583 Y124.808 E.04484
G1 X124.938 Y125.112 F15000
G1 F3000
G1 X125.392 Y124.582 E.02598
G1 X127.5 Y123.9 E.08254
M73 P62 R3
G1 X197.5 Y123.9 E2.60723
G1 X199.138 Y124.295 E.06277
G1 X200.418 Y125.392 E.06277
G1 X201.1 Y127.5 E.08254
G1 X201.1 Y197.5 E2.60723
G1 X200.705 Y199.138 E.06277
G1 X199.608 Y200.418 E.06277
G1 X197.5 Y201.1 E.08254
G1 X127.5 Y201.1 E2.60723
G1 X125.862 Y200.705 E.06277
G1 X124.582 Y199.608 E.06277
M73 P63 R3
G1 X123.9 Y197.5 E.08254
G1 X123.9 Y127.5 E2.60723
G1 X124.295 Y125.862 E.06277
G1 X124.911 Y125.142 E.0353
G1 X125.244 Y125.457 F15000
M73 P63 R3
G1 F3000
G1 X125.833 Y124.836 E.03191
G1 X127.5 Y124.357 E.06459
G1 X197.5 Y124.357 E2.60723
G1 X199.023 Y124.751 E.05859
G1 X200.164 Y125.833 E.05859
G1 X200.643 Y127.5 E.06459
G1 X200.643 Y197.5 E2.60723
G1 X200.249 Y199.023 E.05859
G1 X199.167 Y200.164 E.05859
G1 X197.5 Y200.643 E.06459
G1 X127.5 Y200.643 E2.60723
G1 X125.977 Y200.249 E.05859
M73 P64 R3
G1 X124.836 Y199.167 E.05859
G1 X124.357 Y197.5 E.06459
G1 X124.357 Y127.5 E2.60723
G1 X124.751 Y125.977 E.05859
G1 X125.216 Y125.486 E.02519
M73 P64 R3
G1 X125.519 Y125.812 F15000
G1 F3000
G1 X126.27 Y125.113 E.03821
G1 X127.5 Y124.814 E.04715
G1 X197.5 Y124.814 E2.60723
G1 X198.898 Y125.207 E.05408
G1 X199.887 Y126.27 E.05408
G1 X200.186 Y127.5 E.04715
G1 X200.186 Y197.5 E2.60723
G1 X199.793 Y198.898 E.05408
M73 P65 R3
G1 X198.73 Y199.887 E.05408
G1 X197.5 Y200.186 E.04715
G1 X127.5 Y200.186 E2.60723
G1 X126.102 Y199.793 E.05408
G1 X125.113 Y198.73 E.05408
M73 P65 R3
G1 X124.814 Y197.5 E.04715
G1 X124.814 Y127.5 E2.60723
G1 X125.207 Y126.102 E.05408
G1 X125.49 Y125.839 E.01439
G1 X125.751 Y126.169 F15000
G1 F3000
G1 X126.698 Y125.421 E.04498
G1 X127.5 Y125.271 E.03037
G1 X197.5 Y125.271 E2.60723
G1 X198.761 Y125.662 E.04917
M73 P66 R2
G1 X199.579 Y126.698 E.04917
G1 X199.729 Y127.5 E.03037
G1 X199.729 Y197.5 E2.60723
G1 X199.338 Y198.761 E.04917
G1 X198.302 Y199.579 E.04917
M73 P66 R2
G1 X197.5 Y199.729 E.03037
G1 X127.5 Y199.729 E2.60723
G1 X126.239 Y199.338 E.04917
G1 X125.421 Y198.302 E.04917
G1 X125.271 Y197.5 E.03037
G1 X125.271 Y127.5 E2.60723
G1 X125.662 Y126.239 E.04917
G1 X125.719 Y126.194 E.0027
G1 E-.4 F1800
;WIPE_START
G1 F3000
G1 X126.504 Y125.574 E-.6
;WIPE_END
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 X131.865 Y131.007 Z.6 F15000
G1 X196.186 Y196.186 Z.6
G1 Z.2
M73 P67 R2
G1 E1 F1800
;TYPE:Inner wall
G1 F3000
G1 X128.814 Y196.186 E2.50934
G1 X128.814 Y128.814 E2.50934
G1 X196.186 Y128.814 E2.50934
M73 P67 R2
G1 X196.186 Y196.126 E2.5071
G1 X196.643 Y196.643 F15000
M73 P68 R2
G1 F3000
G1 X128.357 Y196.643 E2.54339
G1 X128.357 Y128.357 E2.54339
G1 X196.643 Y128.357 E2.54339
G1 X196.643 Y196.583 E2.54115
M73 P69 R2
M73 P68 R2
G1 X197.1 Y197.1 F15000
;TYPE:Outer wall
G1 F3000
G1 X127.9 Y197.1 E2.57744
G1 X127.9 Y127.9 E2.57744
G1 X197.1 Y127.9 E2.57744
M73 P69 R2
G1 X197.1 Y197.04 E2.5752
M73 P70 R2
G1 E-.4 F1800
;WIPE_START
G1 F3000
G1 X196.1 Y197.041 E-.6
;WIPE_END
G1 X196.094 Y189.408 Z.6 F15000
G1 X196.049 Y129.879 Z.6
M73 P70 R2
G1 Z.2
G1 E1 F1800
;TYPE:Bottom surface
;WIDTH:0.501638
G1 F6300
G1 X195.327 Y129.157 E.03815
G1 X194.678 Y129.157 E.02425
G1 X195.843 Y130.322 E.06157
G1 X195.843 Y130.97 E.02425
G1 X194.03 Y129.157 E.09587
G1 X193.381 Y129.157 E.02425
G1 X195.843 Y131.619 E.13016
G1 X195.843 Y132.268 E.02425
G1 X192.732 Y129.157 E.16446
G1 X192.083 Y129.157 E.02425
G1 X195.843 Y132.917 E.19875
G1 X195.843 Y133.565 E.02425
G1 X191.435 Y129.157 E.23304
G1 X190.786 Y129.157 E.02425
G1 X195.843 Y134.214 E.26734
G1 X195.843 Y134.863 E.02425
G1 X190.137 Y129.157 E.30163
G1 X189.488 Y129.157 E.02425
G1 X195.843 Y135.512 E.33592
G1 X195.843 Y136.16 E.02425
G1 X188.84 Y129.157 E.37022
M73 P71 R2
G1 X188.191 Y129.157 E.02425
G1 X195.843 Y136.809 E.40451
G1 X195.843 Y137.458 E.02425
G1 X187.542 Y129.157 E.4388
G1 X186.894 Y129.157 E.02425
M73 P71 R2
G1 X195.843 Y138.106 E.4731
G1 X195.843 Y138.755 E.02425
G1 X186.245 Y129.157 E.50739
G1 X185.596 Y129.157 E.02425
G1 X195.843 Y139.404 E.54168
G1 X195.843 Y140.053 E.02425
G1 X184.947 Y129.157 E.57598
G1 X184.299 Y129.157 E.02425
G1 X195.843 Y140.701 E.61027
G1 X195.843 Y141.35 E.02425
G1 X183.65 Y129.157 E.64456
G1 X183.001 Y129.157 E.02425
G1 X195.843 Y141.999 E.67886
G1 X195.843 Y142.648 E.02425
G1 X182.352 Y129.157 E.71315
G1 X181.704 Y129.157 E.02425
G1 X195.843 Y143.296 E.74744
G1 X195.843 Y143.945 E.02425
G1 X181.055 Y129.157 E.78174
G1 X180.406 Y129.157 E.02425
G1 X195.843 Y144.594 E.81603
G1 X195.843 Y145.242 E.02425
G1 X179.758 Y129.157 E.85033
G1 X179.109 Y129.157 E.02425
M73 P72 R2
G1 X195.843 Y145.891 E.88462
G1 X195.843 Y146.54 E.02425
G1 X178.46 Y129.157 E.91891
G1 X177.811 Y129.157 E.02425
G1 X195.843 Y147.189 E.95321
M73 P72 R2
G1 X195.843 Y147.837 E.02425
G1 X177.163 Y129.157 E.9875
G1 X176.514 Y129.157 E.02425
G1 X195.843 Y148.486 E1.02179
G1 X195.843 Y149.135 E.02425
G1 X175.865 Y129.157 E1.05609
G1 X175.216 Y129.157 E.02425
G1 X195.843 Y149.784 E1.09038
G1 X195.843 Y150.432 E.02425
G1 X174.568 Y129.157 E1.12467
G1 X173.919 Y129.157 E.02425
G1 X195.843 Y151.081 E1.15897
G1 X195.843 Y151.73 E.02425
G1 X173.27 Y129.157 E1.19326
G1 X172.622 Y129.157 E.02425
G1 X195.843 Y152.378 E1.22755
G1 X195.843 Y153.027 E.02425
M73 P73 R2
G1 X171.973 Y129.157 E1.26185
G1 X171.324 Y129.157 E.02425
G1 X195.843 Y153.676 E1.29614
G1 X195.843 Y154.325 E.02425
G1 X170.675 Y129.157 E1.33043
M73 P73 R2
G1 X170.027 Y129.157 E.02425
G1 X195.843 Y154.973 E1.36473
G1 X195.843 Y155.622 E.02425
G1 X169.378 Y129.157 E1.39902
G1 X168.729 Y129.157 E.02425
G1 X195.843 Y156.271 E1.43331
G1 X195.843 Y156.92 E.02425
G1 X168.08 Y129.157 E1.46761
G1 X167.432 Y129.157 E.02425
G1 X195.843 Y157.568 E1.5019
G1 X195.843 Y158.217 E.02425
G1 X166.783 Y129.157 E1.53619
G1 X166.134 Y129.157 E.02425
M73 P74 R2
G1 X195.843 Y158.866 E1.57049
G1 X195.843 Y159.514 E.02425
G1 X165.486 Y129.157 E1.60478
G1 X164.837 Y129.157 E.02425
G1 X195.843 Y160.163 E1.63908
M73 P74 R2
G1 X195.843 Y160.812 E.02425
G1 X164.188 Y129.157 E1.67337
G1 X163.539 Y129.157 E.02425
G1 X195.843 Y161.461 E1.70766
G1 X195.843 Y162.109 E.02425
G1 X162.891 Y129.157 E1.74196
G1 X162.242 Y129.157 E.02425
G1 X195.843 Y162.758 E1.77625
G1 X195.843 Y163.407 E.02425
G1 X161.593 Y129.157 E1.81054
G1 X160.945 Y129.157 E.02425
M73 P75 R2
G1 X195.843 Y164.055 E1.84484
G1 X195.843 Y164.704 E.02425
G1 X160.296 Y129.157 E1.87913
G1 X159.647 Y129.157 E.02425
G1 X195.843 Y165.353 E1.91342
M73 P75 R2
G1 X195.843 Y166.002 E.02425
G1 X158.998 Y129.157 E1.94772
G1 X158.35 Y129.157 E.02425
G1 X195.843 Y166.65 E1.98201
G1 X195.843 Y167.299 E.02425
G1 X157.701 Y129.157 E2.0163
G1 X157.052 Y129.157 E.02425
G1 X195.843 Y167.948 E2.0506
G1 X195.843 Y168.597 E.02425
M73 P76 R2
G1 X156.403 Y129.157 E2.08489
G1 X155.755 Y129.157 E.02425
G1 X195.843 Y169.245 E2.11918
G1 X195.843 Y169.894 E.02425
G1 X155.106 Y129.157 E2.15348
M73 P76 R2
G1 X154.457 Y129.157 E.02425
G1 X195.843 Y170.543 E2.18777
G1 X195.843 Y171.191 E.02425
G1 X153.809 Y129.157 E2.22206
G1 X153.16 Y129.157 E.02425
G1 X195.843 Y171.84 E2.25636
G1 X195.843 Y172.489 E.02425
G1 X152.511 Y129.157 E2.29065
G1 X151.862 Y129.157 E.02425
M73 P77 R2
G1 X195.843 Y173.138 E2.32494
G1 X195.843 Y173.786 E.02425
G1 X151.214 Y129.157 E2.35924
G1 X150.565 Y129.157 E.02425
M73 P77 R1
G1 X195.843 Y174.435 E2.39353
M73 P77 R2
G1 X195.843 Y175.084 E.02425
G1 X149.916 Y129.157 E2.42783
G1 X149.267 Y129.157 E.02425
G1 X195.843 Y175.733 E2.46212
M73 P77 R1
G1 X195.843 Y176.381 E.02425
G1 X148.619 Y129.157 E2.49641
G1 X147.97 Y129.157 E.02425
G1 X195.843 Y177.03 E2.53071
M73 P78 R1
G1 X195.843 Y177.679 E.02425
G1 X147.321 Y129.157 E2.565
G1 X146.673 Y129.157 E.02425
G1 X195.843 Y178.327 E2.59929
G1 X195.843 Y178.976 E.02425
M73 P78 R1
G1 X146.024 Y129.157 E2.63359
G1 X145.375 Y129.157 E.02425
G1 X195.843 Y179.625 E2.66788
G1 X195.843 Y180.274 E.02425
G1 X144.726 Y129.157 E2.70217
G1 X144.078 Y129.157 E.02425
M73 P79 R1
G1 X195.843 Y180.922 E2.73647
G1 X195.843 Y181.571 E.02425
G1 X143.429 Y129.157 E2.77076
G1 X142.78 Y129.157 E.02425
G1 X195.843 Y182.22 E2.80505
M73 P79 R1
G1 X195.843 Y182.869 E.02425
G1 X142.131 Y129.157 E2.83935
G1 X141.483 Y129.157 E.02425
G1 X195.843 Y183.517 E2.87364
G1 X195.843 Y184.166 E.02425
G1 X140.834 Y129.157 E2.90793
G1 X140.185 Y129.157 E.02425
M73 P80 R1
G1 X195.843 Y184.815 E2.94223
G1 X195.843 Y185.463 E.02425
G1 X139.537 Y129.157 E2.97652
G1 X138.888 Y129.157 E.02425
G1 X195.843 Y186.112 E3.01081
M73 P80 R1
G1 X195.843 Y186.761 E.02425
G1 X138.239 Y129.157 E3.04511
G1 X137.59 Y129.157 E.02425
G1 X195.843 Y187.41 E3.0794
G1 X195.843 Y188.058 E.02425
M73 P81 R1
G1 X136.942 Y129.157 E3.1137
G1 X136.293 Y129.157 E.02425
G1 X195.843 Y188.707 E3.14799
G1 X195.843 Y189.356 E.02425
G1 X135.644 Y129.157 E3.18228
M73 P81 R1
G1 X134.996 Y129.157 E.02425
G1 X195.843 Y190.004 E3.21658
G1 X195.843 Y190.653 E.02425
G1 X134.347 Y129.157 E3.25087
G1 X133.698 Y129.157 E.02425
M73 P82 R1
G1 X195.843 Y191.302 E3.28516
G1 X195.843 Y191.951 E.02425
G1 X133.049 Y129.157 E3.31946
G1 X132.401 Y129.157 E.02425
G1 X195.843 Y192.599 E3.35375
M73 P82 R1
G1 X195.843 Y193.248 E.02425
G1 X131.752 Y129.157 E3.38804
G1 X131.103 Y129.157 E.02425
G1 X195.843 Y193.897 E3.42234
G1 X195.843 Y194.546 E.02425
M73 P83 R1
G1 X130.454 Y129.157 E3.45663
G1 X129.806 Y129.157 E.02425
G1 X195.843 Y195.194 E3.49092
G1 X195.843 Y195.843 E.02425
G1 X129.157 Y129.157 E3.52522
M73 P83 R1
G1 X129.157 Y129.806 E.02425
G1 X195.194 Y195.843 E3.49093
G1 X194.546 Y195.843 E.02425
G1 X129.157 Y130.454 E3.45663
G1 X129.157 Y131.103 E.02425
M73 P84 R1
G1 X193.897 Y195.843 E3.42234
G1 X193.248 Y195.843 E.02425
G1 X129.157 Y131.752 E3.38805
G1 X129.157 Y132.401 E.02425
G1 X192.599 Y195.843 E3.35375
M73 P84 R1
G1 X191.951 Y195.843 E.02425
G1 X129.157 Y133.049 E3.31946
G1 X129.157 Y133.698 E.02425
G1 X191.302 Y195.843 E3.28516
G1 X190.653 Y195.843 E.02425
M73 P85 R1
G1 X129.157 Y134.347 E3.25087
G1 X129.157 Y134.995 E.02425
G1 X190.005 Y195.843 E3.21658
G1 X189.356 Y195.843 E.02425
G1 X129.157 Y135.644 E3.18228
M73 P85 R1
G1 X129.157 Y136.293 E.02425
G1 X188.707 Y195.843 E3.14799
G1 X188.058 Y195.843 E.02425
G1 X129.157 Y136.942 E3.1137
G1 X129.157 Y137.59 E.02425
M73 P86 R1
G1 X187.41 Y195.843 E3.0794
G1 X186.761 Y195.843 E.02425
G1 X129.157 Y138.239 E3.04511
G1 X129.157 Y138.888 E.02425
G1 X186.112 Y195.843 E3.01082
M73 P86 R1
G1 X185.463 Y195.843 E.02425
G1 X129.157 Y139.537 E2.97652
G1 X129.157 Y140.185 E.02425
G1 X184.815 Y195.843 E2.94223
G1 X184.166 Y195.843 E.02425
M73 P87 R1
G1 X129.157 Y140.834 E2.90794
G1 X129.157 Y141.483 E.02425
G1 X183.517 Y195.843 E2.87364
G1 X182.869 Y195.843 E.02425
G1 X129.157 Y142.131 E2.83935
M73 P87 R1
G1 X129.157 Y142.78 E.02425
G1 X182.22 Y195.843 E2.80506
G1 X181.571 Y195.843 E.02425
G1 X129.157 Y143.429 E2.77076
G1 X129.157 Y144.078 E.02425
G1 X180.922 Y195.843 E2.73647
G1 X180.274 Y195.843 E.02425
M73 P88 R1
G1 X129.157 Y144.726 E2.70218
G1 X129.157 Y145.375 E.02425
G1 X179.625 Y195.843 E2.66788
G1 X178.976 Y195.843 E.02425
G1 X129.157 Y146.024 E2.63359
M73 P88 R1
G1 X129.157 Y146.673 E.02425
G1 X178.327 Y195.843 E2.59929
G1 X177.679 Y195.843 E.02425
M73 P88 R0
G1 X129.157 Y147.321 E2.565
G1 X129.157 Y147.97 E.02425
G1 X177.03 Y195.843 E2.53071
G1 X176.381 Y195.843 E.02425
M73 P89 R0
G1 X129.157 Y148.619 E2.49641
M73 P88 R0
G1 X129.157 Y149.267 E.02425
G1 X175.733 Y195.843 E2.46212
G1 X175.084 Y195.843 E.02425
G1 X129.157 Y149.916 E2.42783
M73 P89 R0
G1 X129.157 Y150.565 E.02425
G1 X174.435 Y195.843 E2.39353
G1 X173.786 Y195.843 E.02425
G1 X129.157 Y151.214 E2.35924
G1 X129.157 Y151.862 E.02425
G1 X173.138 Y195.843 E2.32495
G1 X172.489 Y195.843 E.02425
M73 P90 R0
G1 X129.157 Y152.511 E2.29065
G1 X129.157 Y153.16 E.02425
G1 X171.84 Y195.843 E2.25636
G1 X171.191 Y195.843 E.02425
G1 X129.157 Y153.809 E2.22207
M73 P90 R0
G1 X129.157 Y154.457 E.02425
G1 X170.543 Y195.843 E2.18777
G1 X169.894 Y195.843 E.02425
G1 X129.157 Y155.106 E2.15348
G1 X129.157 Y155.755 E.02425
G1 X169.245 Y195.843 E2.11919
G1 X168.597 Y195.843 E.02425
G1 X129.157 Y156.403 E2.08489
G1 X129.157 Y157.052 E.02425
M73 P91 R0
G1 X167.948 Y195.843 E2.0506
G1 X167.299 Y195.843 E.02425
G1 X129.157 Y157.701 E2.01631
G1 X129.157 Y158.35 E.02425
G1 X166.65 Y195.843 E1.98201
M73 P91 R0
G1 X166.002 Y195.843 E.02425
G1 X129.157 Y158.998 E1.94772
G1 X129.157 Y159.647 E.02425
G1 X165.353 Y195.843 E1.91343
G1 X164.704 Y195.843 E.02425
G1 X129.157 Y160.296 E1.87913
G1 X129.157 Y160.944 E.02425
G1 X164.056 Y195.843 E1.84484
G1 X163.407 Y195.843 E.02425
M73 P92 R0
G1 X129.157 Y161.593 E1.81054
G1 X129.157 Y162.242 E.02425
G1 X162.758 Y195.843 E1.77625
G1 X162.109 Y195.843 E.02425
G1 X129.157 Y162.891 E1.74196
M73 P92 R0
G1 X129.157 Y163.539 E.02425
G1 X161.461 Y195.843 E1.70766
G1 X160.812 Y195.843 E.02425
G1 X129.157 Y164.188 E1.67337
G1 X129.157 Y164.837 E.02425
G1 X160.163 Y195.843 E1.63908
G1 X159.514 Y195.843 E.02425
G1 X129.157 Y165.486 E1.60478
G1 X129.157 Y166.134 E.02425
G1 X158.866 Y195.843 E1.57049
G1 X158.217 Y195.843 E.02425
M73 P93 R0
G1 X129.157 Y166.783 E1.5362
G1 X129.157 Y167.432 E.02425
G1 X157.568 Y195.843 E1.5019
G1 X156.92 Y195.843 E.02425
G1 X129.157 Y168.08 E1.46761
M73 P93 R0
G1 X129.157 Y168.729 E.02425
G1 X156.271 Y195.843 E1.43332
G1 X155.622 Y195.843 E.02425
G1 X129.157 Y169.378 E1.39902
G1 X129.157 Y170.027 E.02425
G1 X154.973 Y195.843 E1.36473
G1 X154.325 Y195.843 E.02425
G1 X129.157 Y170.675 E1.33044
G1 X129.157 Y171.324 E.02425
G1 X153.676 Y195.843 E1.29614
G1 X153.027 Y195.843 E.02425
G1 X129.157 Y171.973 E1.26185
G1 X129.157 Y172.622 E.02425
M73 P94 R0
G1 X152.378 Y195.843 E1.22756
G1 X151.73 Y195.843 E.02425
G1 X129.157 Y173.27 E1.19326
G1 X129.157 Y173.919 E.02425
G1 X151.081 Y195.843 E1.15897
M73 P94 R0
G1 X150.432 Y195.843 E.02425
G1 X129.157 Y174.568 E1.12468
G1 X129.157 Y175.216 E.02425
G1 X149.784 Y195.843 E1.09038
G1 X149.135 Y195.843 E.02425
G1 X129.157 Y175.865 E1.05609
G1 X129.157 Y176.514 E.02425
G1 X148.486 Y195.843 E1.02179
G1 X147.837 Y195.843 E.02425
G1 X129.157 Y177.163 E.9875
G1 X129.157 Y177.811 E.02425
G1 X147.189 Y195.843 E.95321
G1 X146.54 Y195.843 E.02425
G1 X129.157 Y178.46 E.91891
G1 X129.157 Y179.109 E.02425
G1 X145.891 Y195.843 E.88462
G1 X145.242 Y195.843 E.02425
M73 P95 R0
G1 X129.157 Y179.758 E.85033
G1 X129.157 Y180.406 E.02425
G1 X144.594 Y195.843 E.81603
G1 X143.945 Y195.843 E.02425
G1 X129.157 Y181.055 E.78174
M73 P95 R0
G1 X129.157 Y181.704 E.02425
G1 X143.296 Y195.843 E.74745
G1 X142.648 Y195.843 E.02425
G1 X129.157 Y182.352 E.71315
G1 X129.157 Y183.001 E.02425
G1 X141.999 Y195.843 E.67886
G1 X141.35 Y195.843 E.02425
G1 X129.157 Y183.65 E.64457
G1 X129.157 Y184.299 E.02425
G1 X140.701 Y195.843 E.61027
G1 X140.053 Y195.843 E.02425
G1 X129.157 Y184.947 E.57598
G1 X129.157 Y185.596 E.02425
G1 X139.404 Y195.843 E.54169
G1 X138.755 Y195.843 E.02425
G1 X129.157 Y186.245 E.50739
G1 X129.157 Y186.893 E.02425
G1 X138.107 Y195.843 E.4731
G1 X137.458 Y195.843 E.02425
G1 X129.157 Y187.542 E.43881
G1 X129.157 Y188.191 E.02425
G1 X136.809 Y195.843 E.40451
M73 P96 R0
G1 X136.16 Y195.843 E.02425
G1 X129.157 Y188.84 E.37022
G1 X129.157 Y189.488 E.02425
G1 X135.512 Y195.843 E.33592
G1 X134.863 Y195.843 E.02425
M73 P96 R0
G1 X129.157 Y190.137 E.30163
G1 X129.157 Y190.786 E.02425
G1 X134.214 Y195.843 E.26734
G1 X133.565 Y195.843 E.02425
G1 X129.157 Y191.435 E.23304
G1 X129.157 Y192.083 E.02425
G1 X132.917 Y195.843 E.19875
G1 X132.268 Y195.843 E.02425
G1 X129.157 Y192.732 E.16446
G1 X129.157 Y193.381 E.02425
G1 X131.619 Y195.843 E.13016
G1 X130.971 Y195.843 E.02425
G1 X129.157 Y194.029 E.09587
G1 X129.157 Y194.678 E.02425
G1 X130.322 Y195.843 E.06158
G1 X129.673 Y195.843 E.02425
G1 X128.951 Y195.121 E.03816
G1 E-.71429 F1800
;WIPE_START
G1 F6300
G1 X129.658 Y195.828 E-.28571
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
M106 P2 S0
;TYPE:Custom
M141 S0
M104 S0
M140 S0
G1 E-3 F1800
G0 Z3.2 F600
G0 X0 Y0 F12000
G1 Z167 F600
M106 P3 S0
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 525.65
; filament used [cm3] = 1.26
; filament used [g] = 1.57
; filament cost = 0.03
; total filament used [g] = 1.57
; total filament cost = 0.03
; total layers count = 1
; estimated printing time (normal mode) = 8m 46s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 1
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 0
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_filament_colour = ""
; default_filament_profile = "Qidi Generic PLA"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @Qidi XMax3
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = only_one_wall_top;skirt_loops;wall_loops;;print_host;thumbnails
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 1
; draft_shield = disabled
; during_print_exhaust_fan_speed = 100
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 0
; enable_overhang_speed = 1
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 118
; extruder_clearance_height_to_rod = 30
; extruder_clearance_radius = 70
; extruder_colour = #C0C0C0
; extruder_offset = 0x0
; fan_cooling_layer_time = 60
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #C0C0C0
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = " "
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 14
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Qidi Generic PLA"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = " "
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = QIDI
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 2
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; idle_temperature = 0
; independent_support_layer_height = 0
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 15%
; inherits_group = ;;"Qidi X-Max 3 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 50%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_flow = 1
; internal_bridge_speed = 50
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = zig-zag
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_end_gcode = M141 S0\nM104 S0\nM140 S0\nG1 E-3 F1800\nG0 Z{min(max_print_height, max_layer_z + 3)} F600\nG0 X0 Y0 F12000\n{if max_layer_z < max_print_height / 2}G1 Z{max_print_height / 2 + 10} F600{else}G1 Z{min(max_print_height, max_layer_z + 3)}{endif}
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 5000
; machine_max_acceleration_travel = 0,0
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 2
; machine_max_jerk_x = 9
; machine_max_jerk_y = 9
; machine_max_jerk_z = 3
; machine_max_speed_e = 30
; machine_max_speed_x = 600
; machine_max_speed_y = 600
; machine_max_speed_z = 10
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = M0
; machine_start_gcode = PRINT_START\nG28\nM141 S0\nG0 Z50 F600\nM190 S[hot_plate_temp_initial_layer]\nG28 Z\nG29; mesh bed leveling ,comment this code to close it\nG0 X0 Y0 Z50 F6000\nM191 S{overall_chamber_temperature}\nM109 S[nozzle_temperature_initial_layer]\nM106 P3 S255\nM83\nG4 P3000\nG0 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0)} Y{max((min(print_bed_max[1], first_layer_print_min[1] + 80) - 85),0)} Z5 F6000\nG0 Z[initial_layer_print_height] F600\nG1 E3 F1800\nG1 X{(min(print_bed_max[0], first_layer_print_min[0] + 80))} E{85 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1], first_layer_print_min[1] + 80) - 85),0) + 2} E{2 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0)} E{85 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1], first_layer_print_min[1] + 80) - 85),0) + 85} E{83 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0) + 2} E{2 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1], first_layer_print_min[1] + 80) - 85),0) + 3} E{82 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0) + 12} E{-10 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 E{10 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\n
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.28
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = If you want to use Orca's chamber temperature control feature, check that printer.cfg has added the following M191 macro.\nTo add it: go to Fluidd web interface--configuration, copy the following code to the top of the printer.cfg document, SAVE&RESATART  \n\n[gcode_macro M191]\ngcode:\n    {% set s = params.S|float %}\n    {% if s == 0 %}\n        # If target temperature is 0, do nothing\n        M117 Chamber heating cancelled\n    {% else %}\n        SET_HEATER_TEMPERATURE HEATER=chamber_heater TARGET={s}\n        # Orca: uncomment the following line if you want to use heat bed to assist chamber heating\n        M140 S90\n        TEMPERATURE_WAIT SENSOR=\"heater_generic chamber_heater\" MINIMUM={s-1} MAXIMUM={s+1}\n        M117 Chamber at target temperature\n    {% endif %}
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 210
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 3000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 95%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.031
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Qidi X-Max 3 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Qidi XMax3
; printable_area = 0x0,325x0,325x325,0x325
; printable_height = 315
; printer_model = Qidi X-Max 3
; printer_notes = 
; printer_settings_id = Qidi X-Max 3 0.4 nozzle - Copy
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 1
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 15%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 10
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 4
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 270
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 240x240/PNG, 96x96/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = ;TIMELAPSE_TAKE_FRAME\n
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 3
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 60
; bed_shape = 0x0,325x0,325x325,0x325
; first_layer_temperature = 210
; first_layer_height = 0.200
; CONFIG_BLOCK_END


