; HEADER_BLOCK_START
; generated by OrcaSlicer 2.2.0 on 2025-06-04 at 11:47:33
; total layer number: 1
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 140x140 1064
; iVBORw0KGgoAAAANSUhEUgAAAIwAAACMCAYAAACuwEE+AAAC5ElEQVR4Ae3dsW3jQBAFUBbkIi53BW
; 7DidJLlKkHBapAFbg0H2jAOIKQLXG1JGd33gM+cKmBub9Dr0QPAwAAAAAAAAAAAAAAQCovLy9/Brjn
; 7e3t7/V6/Rwz/nuAn0yH5TvH4/FjgKlbgzIfGkcUX+4NyzSOqMTGxhib49Fh0TaJLWkVbZNcjWGxEC
; dQc1DmcUR1Zs1hcUR1ZPyfv/agWIg7sUWraJtO7Dks2qYhEQZlHkMTVMRhmbbNQAyRB8URFUwrwzKN
; hXgHpfdA2iahFltF2+ykp2GZts1AXT0OyjyOqEoyDMt3HFFPaH2xLY2FuECmVtE2TzIsV23zCIPycw
; zNjGG5H0fUYFCWJvURZVjKk65tMj4u106KttEq9dNt2xiW9dLVfZRB2S7NH1GGZfs0eURlvQeKkqYW
; Yq0SJ+HbxrDES8iF2KDET5gjyrC0k12PqK2/6C51sstCrFXaz2ZtY1j6yaptY1D6TfW2MSz9p8rjt0
; HJNzTFR5RhyZtFR5R7IBnzUNtoFZnn17YZJ+pyuTT1A8m6eeh4ciTJ+/v7sqem19dXx1PSFP9exgKc
; K6fT6XOo4XA4fLT0g8vyVP9tr4W4z5zP53U/K6Nt+slmN9Y+C2NYiliI20u1xbaU3w63kzDfIrAQx8
; 7qi20pC3G8hP9ukrYxLEUsxPtl8T1QFBbi7dP8+2IcUdtk98fl2izE66Xbt1Bpm/pJ8VZNbfN8ml1s
; S/mAVnlSv+TZ4/fj6W6xLeXx+368On7GQnw7Ye+BorAQ/49WeZAPaBmWIhkX4nSPy7X5I6Es1vtCPC
; 62A/X1uBBrlZX11DaGZUMtt43Fdict3kdplZ218sIA90DBRD6itEpQ0RZi90CNiNA2WqUxe95HGZaG
; bbkQW2w7scV9lFbpzFoLscW2czUXYq2SRI22MSwJlSzE7oGSW3IfpVX4cu8+yuMyN91aiLUKv5ouxB
; 6XAQAAAAAAAAAAAAAA4KZ/Yu4wU8U/g+sAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 408
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA+UlEQVR4Ae2YwQ3DIAxFGShDdI2swY
; VrL8zBgQmYIKO14oBEUYICBGNX/0mWqp5+/L+FQSkAAABgAtu2vUIIH2vtEX8rSez7/o7i84r/KQnE
; jpfiU7F246zrV8XOjRbxuRtqNT3C2URqVPyySMWO1QaVtRtPdp3cDQrxUwacUnhZw5FaKX4oUmmP4V
; JNA86h691ucBZfdUOC8LJ+PoJb5u/UaZxmnLAkwv9miPNIcXLDOdd3qIk9yEo3vPcyxedQRkr0Rjr9
; cjNrwLXWtHdksVfKnCfcYPFOZIw5xHT9ipZ9ivUzYy1S5IPai+jH3UQa8O49BgAAALjBF4+89dX6Zn
; pSAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=122.5,122.5 POLYGON=[[87.5,87.5],[157.5,87.5],[157.5,157.5],[87.5,157.5],[87.5,87.5]]
M73 P0 R4
M106 S0
M106 P2 S0
;TYPE:Custom
PRINT_START BED=60 HOTEND=210 CHAMBER=0
M83
M140 S60
M104 S210
G4 P3000
G0 X75.9292 Y75.9292 Z5 F6000
G0 Z0.2 F600
G1 E3 F1800
G1 X160.929 E3.4 F3000
G1 Y77.9292 E0.08 F3000
M73 P1 R4
G1 X75.9292 E3.4 F3000
M73 P1 R4
G1 Y160.929 E3.32 F3000
M73 P2 R4
G1 X77.9292 E0.08 F3000
M73 P2 R3
M73 P2 R4
G1 Y78.9292 E3.28 F3000
M73 P2 R3
G1 X78.9292 Z0
M73 P3 R3
G1 X81.9292
M73 P3 R3
G1 Z1 F600
M106 P3 S255
G90
G21
M83 ; use relative distances for extrusion
SET_PRESSURE_ADVANCE ADVANCE=0.042; Override pressure advance value
M106 S0
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.8 F1800
;TIMELAPSE_TAKE_FRAME

;BEFORE_LAYER_CHANGE
;0.2
LOG_Z
G92 E0

;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500 ACCEL_TO_DECEL=250
G1 X82.846 Y83.238 F15000
G1 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Skirt
;WIDTH:0.5
G1 F3000
G1 X84.438 Y81.946 E.07635
G1 X87.5 Y81.158 E.11778
G1 X157.5 Y81.158 E2.60723
G1 X159.708 Y81.555 E.08357
M73 P4 R3
G1 X161.64 Y82.695 E.08357
M73 P4 R3
G1 X163.054 Y84.438 E.08357
G1 X163.842 Y87.5 E.11778
G1 X163.842 Y157.5 E2.60723
G1 X163.445 Y159.708 E.08357
M73 P5 R3
G1 X162.305 Y161.64 E.08357
M73 P5 R3
G1 X160.562 Y163.054 E.08357
G1 X157.5 Y163.842 E.11778
G1 X87.5 Y163.842 E2.60723
G1 X85.292 Y163.445 E.08357
G1 X83.36 Y162.305 E.08357
G1 X81.946 Y160.562 E.08357
G1 X81.158 Y157.5 E.11778
G1 X81.158 Y87.5 E2.60723
G1 X81.555 Y85.292 E.08357
M73 P6 R3
G1 X82.695 Y83.36 E.08357
M73 P6 R3
G1 X82.815 Y83.263 E.00572
G1 X83.148 Y83.539 F15000
G1 F3000
G1 X84.871 Y82.235 E.08047
G1 X87.5 Y81.615 E.10062
G1 X157.5 Y81.615 E2.60723
G1 X159.624 Y82.011 E.08047
M73 P7 R3
G1 X161.461 Y83.148 E.08047
M73 P7 R3
G1 X162.765 Y84.871 E.08047
G1 X163.385 Y87.5 E.10062
G1 X163.385 Y157.5 E2.60723
G1 X162.989 Y159.624 E.08047
G1 X161.852 Y161.461 E.08047
G1 X160.129 Y162.765 E.08047
G1 X157.5 Y163.385 E.10062
G1 X87.5 Y163.385 E2.60723
G1 X85.376 Y162.989 E.08047
M73 P8 R3
G1 X83.539 Y161.852 E.08047
M73 P8 R3
G1 X82.235 Y160.129 E.08047
G1 X81.615 Y157.5 E.10062
G1 X81.615 Y87.5 E2.60723
G1 X82.011 Y85.376 E.08047
M73 P9 R3
G1 X83.127 Y83.573 E.07898
M73 P9 R3
G1 X83.529 Y83.834 F15000
G1 F3000
G1 X83.599 Y83.725 E.00483
G1 X85.3 Y82.538 E.07726
G1 X87.5 Y82.072 E.08376
G1 X157.5 Y82.072 E2.60723
G1 X159.536 Y82.468 E.07726
G1 X161.275 Y83.599 E.07726
G1 X162.462 Y85.3 E.07726
G1 X162.928 Y87.5 E.08376
G1 X162.928 Y157.5 E2.60723
G1 X162.532 Y159.536 E.07726
M73 P10 R3
G1 X161.401 Y161.275 E.07726
M73 P10 R3
G1 X159.7 Y162.462 E.07726
G1 X157.5 Y162.928 E.08376
G1 X87.5 Y162.928 E2.60723
G1 X85.464 Y162.532 E.07726
M73 P11 R3
G1 X83.725 Y161.401 E.07726
M73 P11 R3
G1 X82.538 Y159.7 E.07726
G1 X82.072 Y157.5 E.08376
G1 X82.072 Y87.5 E2.60723
G1 X82.468 Y85.464 E.07726
G1 X83.507 Y83.867 E.07094
G1 X83.9 Y84.138 F15000
G1 F3000
G1 X84.05 Y83.921 E.00981
G1 X85.724 Y82.857 E.0739
G1 X87.5 Y82.529 E.06726
G1 X157.5 Y82.529 E2.60723
G1 X159.444 Y82.925 E.0739
M73 P12 R3
G1 X161.079 Y84.05 E.0739
M73 P12 R3
G1 X162.143 Y85.724 E.0739
G1 X162.471 Y87.5 E.06726
G1 X162.471 Y157.5 E2.60723
G1 X162.075 Y159.444 E.0739
M73 P13 R3
G1 X160.95 Y161.079 E.0739
M73 P13 R3
G1 X159.276 Y162.143 E.0739
G1 X157.5 Y162.471 E.06726
G1 X87.5 Y162.471 E2.60723
G1 X85.556 Y162.075 E.0739
G1 X83.921 Y160.95 E.0739
G1 X82.857 Y159.276 E.0739
G1 X82.529 Y157.5 E.06726
G1 X82.529 Y87.5 E2.60723
G1 X82.925 Y85.556 E.0739
M73 P14 R3
G1 X83.878 Y84.171 E.0626
M73 P14 R3
G1 X84.261 Y84.452 F15000
G1 F3000
G1 X84.499 Y84.128 E.01498
G1 X86.142 Y83.195 E.07039
G1 X87.5 Y82.986 E.05116
G1 X157.5 Y82.986 E2.60723
G1 X159.348 Y83.382 E.07039
M73 P15 R3
G1 X160.872 Y84.499 E.07039
M73 P15 R3
G1 X161.805 Y86.142 E.07039
G1 X162.014 Y87.5 E.05116
G1 X162.014 Y157.5 E2.60723
G1 X161.618 Y159.348 E.07039
G1 X160.501 Y160.872 E.07039
G1 X158.858 Y161.805 E.07039
G1 X157.5 Y162.014 E.05116
G1 X87.5 Y162.014 E2.60723
G1 X85.652 Y161.618 E.07039
M73 P16 R3
G1 X84.128 Y160.501 E.07039
M73 P16 R3
G1 X83.195 Y158.858 E.07039
G1 X82.986 Y157.5 E.05116
G1 X82.986 Y87.5 E2.60723
G1 X83.382 Y85.652 E.07039
M73 P17 R3
G1 X84.238 Y84.485 E.05392
M73 P17 R3
G1 X84.608 Y84.777 F15000
G1 F3000
G1 X84.946 Y84.348 E.02036
G1 X86.552 Y83.555 E.06669
G1 X87.5 Y83.443 E.03555
G1 X157.5 Y83.443 E2.60723
G1 X159.246 Y83.838 E.06669
G1 X160.652 Y84.946 E.06669
G1 X161.445 Y86.552 E.06669
G1 X161.557 Y87.5 E.03555
G1 X161.557 Y157.5 E2.60723
G1 X161.162 Y159.246 E.06669
M73 P18 R3
G1 X160.054 Y160.652 E.06669
M73 P18 R3
G1 X158.448 Y161.445 E.06669
G1 X157.5 Y161.557 E.03555
G1 X87.5 Y161.557 E2.60723
G1 X85.754 Y161.162 E.06669
M73 P19 R3
G1 X84.348 Y160.054 E.06669
M73 P19 R3
G1 X83.555 Y158.448 E.06669
G1 X83.443 Y157.5 E.03555
G1 X83.443 Y87.5 E2.60723
G1 X83.838 Y85.754 E.06669
G1 X84.583 Y84.808 E.04484
G1 X84.938 Y85.112 F15000
G1 F3000
G1 X85.392 Y84.582 E.02598
G1 X87.5 Y83.9 E.08254
G1 X157.5 Y83.9 E2.60723
G1 X159.138 Y84.295 E.06277
M73 P20 R3
G1 X160.418 Y85.392 E.06277
M73 P20 R3
G1 X161.1 Y87.5 E.08254
G1 X161.1 Y157.5 E2.60723
G1 X160.705 Y159.138 E.06277
M73 P21 R3
G1 X159.608 Y160.418 E.06277
M73 P21 R3
G1 X157.5 Y161.1 E.08254
G1 X87.5 Y161.1 E2.60723
G1 X85.862 Y160.705 E.06277
G1 X84.582 Y159.608 E.06277
G1 X83.9 Y157.5 E.08254
G1 X83.9 Y87.5 E2.60723
G1 X84.295 Y85.862 E.06277
M73 P22 R3
G1 X84.911 Y85.142 E.0353
M73 P22 R3
G1 X85.244 Y85.457 F15000
G1 F3000
G1 X85.833 Y84.836 E.03191
G1 X87.5 Y84.357 E.06459
G1 X157.5 Y84.357 E2.60723
G1 X159.023 Y84.751 E.05859
M73 P23 R3
G1 X160.164 Y85.833 E.05859
M73 P23 R3
G1 X160.643 Y87.5 E.06459
G1 X160.643 Y157.5 E2.60723
G1 X160.249 Y159.023 E.05859
G1 X159.167 Y160.164 E.05859
G1 X157.5 Y160.643 E.06459
G1 X87.5 Y160.643 E2.60723
G1 X85.977 Y160.249 E.05859
M73 P24 R3
G1 X84.836 Y159.167 E.05859
M73 P24 R3
G1 X84.357 Y157.5 E.06459
G1 X84.357 Y87.5 E2.60723
G1 X84.751 Y85.977 E.05859
M73 P25 R3
G1 X85.216 Y85.486 E.02519
M73 P25 R3
G1 X85.519 Y85.812 F15000
G1 F3000
G1 X86.27 Y85.113 E.03821
G1 X87.5 Y84.814 E.04715
G1 X157.5 Y84.814 E2.60723
G1 X158.898 Y85.207 E.05408
G1 X159.887 Y86.27 E.05408
G1 X160.186 Y87.5 E.04715
G1 X160.186 Y157.5 E2.60723
G1 X159.793 Y158.898 E.05408
M73 P26 R3
G1 X158.73 Y159.887 E.05408
M73 P26 R3
G1 X157.5 Y160.186 E.04715
G1 X87.5 Y160.186 E2.60723
G1 X86.102 Y159.793 E.05408
M73 P27 R3
G1 X85.113 Y158.73 E.05408
M73 P27 R3
G1 X84.814 Y157.5 E.04715
M73 P27 R2
G1 X84.814 Y87.5 E2.60723
M73 P27 R2
G1 X85.207 Y86.102 E.05408
G1 X85.49 Y85.839 E.01439
G1 X85.751 Y86.169 F15000
G1 F3000
G1 X86.698 Y85.421 E.04498
G1 X87.5 Y85.271 E.03037
G1 X157.5 Y85.271 E2.60723
G1 X158.761 Y85.662 E.04917
M73 P28 R2
G1 X159.579 Y86.698 E.04917
M73 P28 R2
G1 X159.729 Y87.5 E.03037
G1 X159.729 Y157.5 E2.60723
G1 X159.338 Y158.761 E.04917
M73 P29 R2
G1 X158.302 Y159.579 E.04917
M73 P29 R2
G1 X157.5 Y159.729 E.03037
G1 X87.5 Y159.729 E2.60723
G1 X86.239 Y159.338 E.04917
G1 X85.421 Y158.302 E.04917
G1 X85.271 Y157.5 E.03037
G1 X85.271 Y87.5 E2.60723
G1 X85.662 Y86.239 E.04917
M73 P30 R2
G1 X85.719 Y86.194 E.0027
;WIPE_START
M73 P30 R2
G1 X86.698 Y85.421 E-.49904
G1 X87.438 Y85.283 E-.30096
;WIPE_END
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 X92.751 Y90.763 Z.6 F15000
G1 X156.186 Y156.186 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Inner wall
G1 F3000
G1 X88.814 Y156.186 E2.50934
G1 X88.814 Y88.814 E2.50934
M73 P31 R2
G1 X156.186 Y88.814 E2.50934
M73 P31 R2
G1 X156.186 Y156.126 E2.5071
M73 P32 R2
G1 X156.643 Y156.643 F15000
M73 P33 R2
M73 P32 R2
G1 F3000
M73 P33 R2
G1 X88.357 Y156.643 E2.54339
G1 X88.357 Y88.357 E2.54339
G1 X156.643 Y88.357 E2.54339
M73 P34 R2
G1 X156.643 Y156.583 E2.54115
M73 P34 R2
G1 X157.1 Y157.1 F15000
M73 P35 R2
;TYPE:Outer wall
G1 F3000
M73 P35 R2
G1 X87.9 Y157.1 E2.57744
G1 X87.9 Y87.9 E2.57744
M73 P36 R2
G1 X157.1 Y87.9 E2.57744
M73 P36 R2
G1 X157.1 Y157.04 E2.5752
M73 P37 R2
;WIPE_START
G1 X155.1 Y157.042 E-.8
;WIPE_END
M73 P37 R2
G1 X155.208 Y149.41 Z.6 F15000
G1 X156.049 Y89.879 Z.6
G1 Z.2
M73 P38 R2
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.501638
M73 P38 R2
G1 F6300
G1 X155.327 Y89.157 E.03815
G1 X154.678 Y89.157 E.02425
G1 X155.843 Y90.322 E.06157
G1 X155.843 Y90.97 E.02425
G1 X154.03 Y89.157 E.09587
G1 X153.381 Y89.157 E.02425
G1 X155.843 Y91.619 E.13016
G1 X155.843 Y92.268 E.02425
G1 X152.732 Y89.157 E.16446
G1 X152.083 Y89.157 E.02425
G1 X155.843 Y92.917 E.19875
G1 X155.843 Y93.565 E.02425
G1 X151.435 Y89.157 E.23304
G1 X150.786 Y89.157 E.02425
G1 X155.843 Y94.214 E.26734
G1 X155.843 Y94.863 E.02425
G1 X150.137 Y89.157 E.30163
G1 X149.488 Y89.157 E.02425
G1 X155.843 Y95.512 E.33592
M73 P39 R2
G1 X155.843 Y96.16 E.02425
M73 P39 R2
G1 X148.84 Y89.157 E.37022
G1 X148.191 Y89.157 E.02425
G1 X155.843 Y96.809 E.40451
G1 X155.843 Y97.458 E.02425
G1 X147.542 Y89.157 E.4388
G1 X146.894 Y89.157 E.02425
G1 X155.843 Y98.106 E.4731
G1 X155.843 Y98.755 E.02425
G1 X146.245 Y89.157 E.50739
G1 X145.596 Y89.157 E.02425
G1 X155.843 Y99.404 E.54168
G1 X155.843 Y100.053 E.02425
G1 X144.947 Y89.157 E.57598
G1 X144.299 Y89.157 E.02425
M73 P40 R2
G1 X155.843 Y100.701 E.61027
M73 P40 R2
G1 X155.843 Y101.35 E.02425
G1 X143.65 Y89.157 E.64456
G1 X143.001 Y89.157 E.02425
G1 X155.843 Y101.999 E.67886
G1 X155.843 Y102.648 E.02425
G1 X142.352 Y89.157 E.71315
G1 X141.704 Y89.157 E.02425
G1 X155.843 Y103.296 E.74744
G1 X155.843 Y103.945 E.02425
G1 X141.055 Y89.157 E.78174
G1 X140.406 Y89.157 E.02425
M73 P41 R2
G1 X155.843 Y104.594 E.81603
M73 P41 R2
G1 X155.843 Y105.242 E.02425
G1 X139.758 Y89.157 E.85033
G1 X139.109 Y89.157 E.02425
G1 X155.843 Y105.891 E.88462
G1 X155.843 Y106.54 E.02425
G1 X138.46 Y89.157 E.91891
G1 X137.811 Y89.157 E.02425
G1 X155.843 Y107.189 E.95321
G1 X155.843 Y107.837 E.02425
G1 X137.163 Y89.157 E.9875
G1 X136.514 Y89.157 E.02425
M73 P42 R2
G1 X155.843 Y108.486 E1.02179
M73 P42 R2
G1 X155.843 Y109.135 E.02425
G1 X135.865 Y89.157 E1.05609
G1 X135.216 Y89.157 E.02425
G1 X155.843 Y109.784 E1.09038
G1 X155.843 Y110.432 E.02425
G1 X134.568 Y89.157 E1.12467
G1 X133.919 Y89.157 E.02425
G1 X155.843 Y111.081 E1.15897
G1 X155.843 Y111.73 E.02425
M73 P43 R2
G1 X133.27 Y89.157 E1.19326
M73 P43 R2
G1 X132.622 Y89.157 E.02425
G1 X155.843 Y112.378 E1.22755
G1 X155.843 Y113.027 E.02425
G1 X131.973 Y89.157 E1.26185
G1 X131.324 Y89.157 E.02425
G1 X155.843 Y113.676 E1.29614
G1 X155.843 Y114.325 E.02425
M73 P44 R2
G1 X130.675 Y89.157 E1.33043
M73 P44 R2
G1 X130.027 Y89.157 E.02425
G1 X155.843 Y114.973 E1.36473
G1 X155.843 Y115.622 E.02425
G1 X129.378 Y89.157 E1.39902
G1 X128.729 Y89.157 E.02425
G1 X155.843 Y116.271 E1.43331
G1 X155.843 Y116.92 E.02425
M73 P45 R2
G1 X128.08 Y89.157 E1.46761
M73 P45 R2
G1 X127.432 Y89.157 E.02425
G1 X155.843 Y117.568 E1.5019
G1 X155.843 Y118.217 E.02425
G1 X126.783 Y89.157 E1.53619
G1 X126.134 Y89.157 E.02425
G1 X155.843 Y118.866 E1.57049
G1 X155.843 Y119.514 E.02425
M73 P46 R2
G1 X125.486 Y89.157 E1.60478
M73 P46 R2
G1 X124.837 Y89.157 E.02425
G1 X155.843 Y120.163 E1.63908
G1 X155.843 Y120.812 E.02425
G1 X124.188 Y89.157 E1.67337
G1 X123.539 Y89.157 E.02425
G1 X155.843 Y121.461 E1.70766
G1 X155.843 Y122.109 E.02425
M73 P47 R2
G1 X122.891 Y89.157 E1.74196
M73 P47 R2
G1 X122.242 Y89.157 E.02425
G1 X155.843 Y122.758 E1.77625
G1 X155.843 Y123.407 E.02425
G1 X121.593 Y89.157 E1.81054
G1 X120.945 Y89.157 E.02425
G1 X155.843 Y124.055 E1.84484
G1 X155.843 Y124.704 E.02425
M73 P48 R2
G1 X120.296 Y89.157 E1.87913
M73 P48 R2
G1 X119.647 Y89.157 E.02425
G1 X155.843 Y125.353 E1.91342
G1 X155.843 Y126.002 E.02425
G1 X118.998 Y89.157 E1.94772
G1 X118.35 Y89.157 E.02425
M73 P49 R2
G1 X155.843 Y126.65 E1.98201
M73 P49 R2
G1 X155.843 Y127.299 E.02425
G1 X117.701 Y89.157 E2.0163
G1 X117.052 Y89.157 E.02425
G1 X155.843 Y127.948 E2.0506
G1 X155.843 Y128.597 E.02425
G1 X116.403 Y89.157 E2.08489
G1 X115.755 Y89.157 E.02425
M73 P50 R2
G1 X155.843 Y129.245 E2.11918
M73 P50 R2
G1 X155.843 Y129.894 E.02425
G1 X115.106 Y89.157 E2.15348
G1 X114.457 Y89.157 E.02425
G1 X155.843 Y130.543 E2.18777
G1 X155.843 Y131.191 E.02425
M73 P51 R2
G1 X113.809 Y89.157 E2.22206
M73 P51 R2
G1 X113.16 Y89.157 E.02425
M73 P51 R1
G1 X155.843 Y131.84 E2.25636
M73 P51 R1
G1 X155.843 Y132.489 E.02425
G1 X112.511 Y89.157 E2.29065
G1 X111.862 Y89.157 E.02425
M73 P52 R1
G1 X155.843 Y133.138 E2.32494
M73 P52 R1
G1 X155.843 Y133.786 E.02425
G1 X111.214 Y89.157 E2.35924
G1 X110.565 Y89.157 E.02425
G1 X155.843 Y134.435 E2.39353
G1 X155.843 Y135.084 E.02425
M73 P53 R1
G1 X109.916 Y89.157 E2.42783
M73 P53 R1
G1 X109.267 Y89.157 E.02425
G1 X155.843 Y135.733 E2.46212
G1 X155.843 Y136.381 E.02425
G1 X108.619 Y89.157 E2.49641
G1 X107.97 Y89.157 E.02425
M73 P54 R1
G1 X155.843 Y137.03 E2.53071
M73 P54 R1
G1 X155.843 Y137.679 E.02425
G1 X107.321 Y89.157 E2.565
G1 X106.673 Y89.157 E.02425
G1 X155.843 Y138.327 E2.59929
G1 X155.843 Y138.976 E.02425
M73 P55 R1
G1 X106.024 Y89.157 E2.63359
M73 P55 R1
G1 X105.375 Y89.157 E.02425
G1 X155.843 Y139.625 E2.66788
G1 X155.843 Y140.274 E.02425
M73 P56 R1
G1 X104.726 Y89.157 E2.70217
M73 P56 R1
G1 X104.078 Y89.157 E.02425
G1 X155.843 Y140.922 E2.73647
G1 X155.843 Y141.571 E.02425
G1 X103.429 Y89.157 E2.77076
G1 X102.78 Y89.157 E.02425
M73 P57 R1
G1 X155.843 Y142.22 E2.80505
M73 P57 R1
G1 X155.843 Y142.869 E.02425
G1 X102.131 Y89.157 E2.83935
G1 X101.483 Y89.157 E.02425
G1 X155.843 Y143.517 E2.87364
G1 X155.843 Y144.166 E.02425
M73 P58 R1
G1 X100.834 Y89.157 E2.90793
M73 P58 R1
G1 X100.185 Y89.157 E.02425
G1 X155.843 Y144.815 E2.94223
G1 X155.843 Y145.463 E.02425
M73 P59 R1
G1 X99.537 Y89.157 E2.97652
M73 P59 R1
G1 X98.888 Y89.157 E.02425
G1 X155.843 Y146.112 E3.01081
G1 X155.843 Y146.761 E.02425
G1 X98.239 Y89.157 E3.04511
G1 X97.59 Y89.157 E.02425
M73 P60 R1
G1 X155.843 Y147.41 E3.0794
M73 P60 R1
G1 X155.843 Y148.058 E.02425
G1 X96.942 Y89.157 E3.1137
G1 X96.293 Y89.157 E.02425
M73 P61 R1
G1 X155.843 Y148.707 E3.14799
M73 P61 R1
G1 X155.843 Y149.356 E.02425
G1 X95.644 Y89.157 E3.18228
G1 X94.996 Y89.157 E.02425
G1 X155.843 Y150.004 E3.21658
M73 P62 R1
G1 X155.843 Y150.653 E.02425
M73 P62 R1
G1 X94.347 Y89.157 E3.25087
G1 X93.698 Y89.157 E.02425
G1 X155.843 Y151.302 E3.28516
G1 X155.843 Y151.951 E.02425
M73 P63 R1
G1 X93.049 Y89.157 E3.31946
M73 P63 R1
G1 X92.401 Y89.157 E.02425
G1 X155.843 Y152.599 E3.35375
G1 X155.843 Y153.248 E.02425
M73 P64 R1
G1 X91.752 Y89.157 E3.38804
M73 P64 R1
G1 X91.103 Y89.157 E.02425
G1 X155.843 Y153.897 E3.42234
G1 X155.843 Y154.546 E.02425
M73 P65 R1
G1 X90.454 Y89.157 E3.45663
M73 P65 R1
G1 X89.806 Y89.157 E.02425
G1 X155.843 Y155.194 E3.49092
G1 X155.843 Y155.843 E.02425
G1 X89.157 Y89.157 E3.52522
G1 X89.157 Y89.806 E.02425
M73 P66 R1
G1 X155.194 Y155.843 E3.49093
M73 P66 R1
G1 X154.546 Y155.843 E.02425
G1 X89.157 Y90.454 E3.45663
G1 X89.157 Y91.103 E.02425
M73 P67 R1
G1 X153.897 Y155.843 E3.42234
M73 P67 R1
G1 X153.248 Y155.843 E.02425
G1 X89.157 Y91.752 E3.38805
G1 X89.157 Y92.401 E.02425
M73 P68 R1
G1 X152.599 Y155.843 E3.35375
M73 P68 R1
G1 X151.951 Y155.843 E.02425
G1 X89.157 Y93.049 E3.31946
G1 X89.157 Y93.698 E.02425
M73 P69 R1
G1 X151.302 Y155.843 E3.28516
M73 P69 R1
G1 X150.653 Y155.843 E.02425
G1 X89.157 Y94.347 E3.25087
G1 X89.157 Y94.995 E.02425
G1 X150.005 Y155.843 E3.21658
G1 X149.356 Y155.843 E.02425
M73 P70 R1
G1 X89.157 Y95.644 E3.18228
M73 P70 R1
G1 X89.157 Y96.293 E.02425
G1 X148.707 Y155.843 E3.14799
G1 X148.058 Y155.843 E.02425
M73 P71 R1
G1 X89.157 Y96.942 E3.1137
M73 P71 R1
G1 X89.157 Y97.59 E.02425
G1 X147.41 Y155.843 E3.0794
G1 X146.761 Y155.843 E.02425
M73 P72 R1
G1 X89.157 Y98.239 E3.04511
M73 P72 R1
G1 X89.157 Y98.888 E.02425
G1 X146.112 Y155.843 E3.01082
G1 X145.463 Y155.843 E.02425
G1 X89.157 Y99.537 E2.97652
G1 X89.157 Y100.185 E.02425
M73 P73 R1
G1 X144.815 Y155.843 E2.94223
M73 P73 R1
G1 X144.166 Y155.843 E.02425
G1 X89.157 Y100.834 E2.90794
G1 X89.157 Y101.483 E.02425
M73 P74 R1
G1 X143.517 Y155.843 E2.87364
M73 P74 R1
G1 X142.869 Y155.843 E.02425
G1 X89.157 Y102.131 E2.83935
G1 X89.157 Y102.78 E.02425
G1 X142.22 Y155.843 E2.80506
G1 X141.571 Y155.843 E.02425
M73 P75 R1
G1 X89.157 Y103.429 E2.77076
M73 P75 R1
G1 X89.157 Y104.078 E.02425
G1 X140.922 Y155.843 E2.73647
G1 X140.274 Y155.843 E.02425
M73 P75 R0
G1 X89.157 Y104.726 E2.70218
M73 P75 R0
G1 X89.157 Y105.375 E.02425
M73 P76 R0
G1 X139.625 Y155.843 E2.66788
M73 P76 R0
G1 X138.976 Y155.843 E.02425
G1 X89.157 Y106.024 E2.63359
G1 X89.157 Y106.673 E.02425
M73 P77 R0
G1 X138.327 Y155.843 E2.59929
M73 P77 R0
G1 X137.679 Y155.843 E.02425
G1 X89.157 Y107.321 E2.565
G1 X89.157 Y107.97 E.02425
G1 X137.03 Y155.843 E2.53071
G1 X136.381 Y155.843 E.02425
M73 P78 R0
G1 X89.157 Y108.619 E2.49641
M73 P78 R0
G1 X89.157 Y109.267 E.02425
G1 X135.733 Y155.843 E2.46212
G1 X135.084 Y155.843 E.02425
G1 X89.157 Y109.916 E2.42783
G1 X89.157 Y110.565 E.02425
M73 P79 R0
G1 X134.435 Y155.843 E2.39353
M73 P79 R0
G1 X133.786 Y155.843 E.02425
G1 X89.157 Y111.214 E2.35924
G1 X89.157 Y111.862 E.02425
G1 X133.138 Y155.843 E2.32495
G1 X132.489 Y155.843 E.02425
M73 P80 R0
G1 X89.157 Y112.511 E2.29065
M73 P80 R0
G1 X89.157 Y113.16 E.02425
G1 X131.84 Y155.843 E2.25636
G1 X131.191 Y155.843 E.02425
G1 X89.157 Y113.809 E2.22207
G1 X89.157 Y114.457 E.02425
M73 P81 R0
G1 X130.543 Y155.843 E2.18777
M73 P81 R0
G1 X129.894 Y155.843 E.02425
G1 X89.157 Y115.106 E2.15348
G1 X89.157 Y115.755 E.02425
G1 X129.245 Y155.843 E2.11919
G1 X128.597 Y155.843 E.02425
M73 P82 R0
G1 X89.157 Y116.403 E2.08489
M73 P82 R0
G1 X89.157 Y117.052 E.02425
G1 X127.948 Y155.843 E2.0506
G1 X127.299 Y155.843 E.02425
G1 X89.157 Y117.701 E2.01631
G1 X89.157 Y118.35 E.02425
M73 P83 R0
G1 X126.65 Y155.843 E1.98201
M73 P83 R0
G1 X126.002 Y155.843 E.02425
G1 X89.157 Y118.998 E1.94772
G1 X89.157 Y119.647 E.02425
G1 X125.353 Y155.843 E1.91343
G1 X124.704 Y155.843 E.02425
G1 X89.157 Y120.296 E1.87913
G1 X89.157 Y120.944 E.02425
M73 P84 R0
G1 X124.056 Y155.843 E1.84484
M73 P84 R0
G1 X123.407 Y155.843 E.02425
G1 X89.157 Y121.593 E1.81054
G1 X89.157 Y122.242 E.02425
G1 X122.758 Y155.843 E1.77625
G1 X122.109 Y155.843 E.02425
M73 P85 R0
G1 X89.157 Y122.891 E1.74196
M73 P85 R0
G1 X89.157 Y123.539 E.02425
G1 X121.461 Y155.843 E1.70766
G1 X120.812 Y155.843 E.02425
G1 X89.157 Y124.188 E1.67337
G1 X89.157 Y124.837 E.02425
G1 X120.163 Y155.843 E1.63908
G1 X119.514 Y155.843 E.02425
M73 P86 R0
G1 X89.157 Y125.486 E1.60478
M73 P86 R0
G1 X89.157 Y126.134 E.02425
G1 X118.866 Y155.843 E1.57049
G1 X118.217 Y155.843 E.02425
G1 X89.157 Y126.783 E1.5362
G1 X89.157 Y127.432 E.02425
G1 X117.568 Y155.843 E1.5019
G1 X116.92 Y155.843 E.02425
M73 P87 R0
G1 X89.157 Y128.08 E1.46761
M73 P87 R0
G1 X89.157 Y128.729 E.02425
G1 X116.271 Y155.843 E1.43332
G1 X115.622 Y155.843 E.02425
G1 X89.157 Y129.378 E1.39902
G1 X89.157 Y130.027 E.02425
G1 X114.973 Y155.843 E1.36473
G1 X114.325 Y155.843 E.02425
M73 P88 R0
G1 X89.157 Y130.675 E1.33044
M73 P88 R0
G1 X89.157 Y131.324 E.02425
G1 X113.676 Y155.843 E1.29614
G1 X113.027 Y155.843 E.02425
G1 X89.157 Y131.973 E1.26185
G1 X89.157 Y132.622 E.02425
G1 X112.378 Y155.843 E1.22756
G1 X111.73 Y155.843 E.02425
G1 X89.157 Y133.27 E1.19326
G1 X89.157 Y133.919 E.02425
M73 P89 R0
G1 X111.081 Y155.843 E1.15897
M73 P89 R0
G1 X110.432 Y155.843 E.02425
G1 X89.157 Y134.568 E1.12468
G1 X89.157 Y135.216 E.02425
G1 X109.784 Y155.843 E1.09038
G1 X109.135 Y155.843 E.02425
G1 X89.157 Y135.865 E1.05609
G1 X89.157 Y136.514 E.02425
G1 X108.486 Y155.843 E1.02179
M73 P90 R0
G1 X107.837 Y155.843 E.02425
M73 P90 R0
G1 X89.157 Y137.163 E.9875
G1 X89.157 Y137.811 E.02425
G1 X107.189 Y155.843 E.95321
G1 X106.54 Y155.843 E.02425
G1 X89.157 Y138.46 E.91891
G1 X89.157 Y139.109 E.02425
G1 X105.891 Y155.843 E.88462
G1 X105.242 Y155.843 E.02425
G1 X89.157 Y139.758 E.85033
G1 X89.157 Y140.406 E.02425
M73 P91 R0
G1 X104.594 Y155.843 E.81603
M73 P91 R0
G1 X103.945 Y155.843 E.02425
G1 X89.157 Y141.055 E.78174
G1 X89.157 Y141.704 E.02425
G1 X103.296 Y155.843 E.74745
G1 X102.648 Y155.843 E.02425
G1 X89.157 Y142.352 E.71315
G1 X89.157 Y143.001 E.02425
G1 X101.999 Y155.843 E.67886
G1 X101.35 Y155.843 E.02425
G1 X89.157 Y143.65 E.64457
G1 X89.157 Y144.299 E.02425
M73 P92 R0
G1 X100.701 Y155.843 E.61027
M73 P92 R0
G1 X100.053 Y155.843 E.02425
G1 X89.157 Y144.947 E.57598
G1 X89.157 Y145.596 E.02425
G1 X99.404 Y155.843 E.54169
G1 X98.755 Y155.843 E.02425
G1 X89.157 Y146.245 E.50739
G1 X89.157 Y146.893 E.02425
G1 X98.107 Y155.843 E.4731
G1 X97.458 Y155.843 E.02425
G1 X89.157 Y147.542 E.43881
G1 X89.157 Y148.191 E.02425
G1 X96.809 Y155.843 E.40451
M73 P93 R0
G1 X96.16 Y155.843 E.02425
M73 P93 R0
G1 X89.157 Y148.84 E.37022
G1 X89.157 Y149.488 E.02425
G1 X95.512 Y155.843 E.33592
G1 X94.863 Y155.843 E.02425
G1 X89.157 Y150.137 E.30163
G1 X89.157 Y150.786 E.02425
G1 X94.214 Y155.843 E.26734
G1 X93.565 Y155.843 E.02425
G1 X89.157 Y151.435 E.23304
G1 X89.157 Y152.083 E.02425
G1 X92.917 Y155.843 E.19875
G1 X92.268 Y155.843 E.02425
G1 X89.157 Y152.732 E.16446
G1 X89.157 Y153.381 E.02425
G1 X91.619 Y155.843 E.13016
G1 X90.971 Y155.843 E.02425
G1 X89.157 Y154.029 E.09587
G1 X89.157 Y154.678 E.02425
G1 X90.322 Y155.843 E.06158
M73 P94 R0
G1 X89.673 Y155.843 E.02425
M73 P94 R0
G1 X88.951 Y155.121 E.03816
G1 E-.22857 F1800
;WIPE_START
G1 F6300
G1 X89.673 Y155.843 E-.29165
G1 X90.322 Y155.843 E-.18535
G1 X90.088 Y155.609 E-.09443
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
M106 P2 S0
;TYPE:Custom
M141 S0
M104 S0
M140 S0
G1 E-3 F1800
G0 Z3.2 F600
G0 X0 Y0 F12000
G1 Z130 F600
M106 P3 S0
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 525.65
; filament used [cm3] = 1.26
; filament used [g] = 1.57
; filament cost = 0.03
; total filament used [g] = 1.57
; total filament cost = 0.03
; total layers count = 1
; estimated printing time (normal mode) = 4m 6s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 1
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 25x245,25x240,115x240,115x245,208x245,208x240,245x240,245x245,208x245
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 0
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_filament_colour = ""
; default_filament_profile = "Qidi Generic PLA @Qidi Q1 Pro 0.4 nozzle"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @Qidi Q1 Pro
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = only_one_wall_top;skirt_loops;wall_loops;;thumbnails
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 1
; draft_shield = disabled
; during_print_exhaust_fan_speed = 100
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 0
; enable_overhang_speed = 1
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 120
; extruder_clearance_height_to_rod = 40
; extruder_clearance_radius = 70
; extruder_colour = #C0C0C0
; extruder_offset = 0x0
; fan_cooling_layer_time = 60
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #C0C0C0
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = " "
; filament_flow_ratio = 0.98
; filament_ids = GFB99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 14
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Qidi Generic PLA @Qidi Q1 Pro 0.4 nozzle"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = " "
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = QIDI
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 2
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; idle_temperature = 0
; independent_support_layer_height = 0
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 15%
; inherits_group = ;;"Qidi Q1 Pro 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 50%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_flow = 1
; internal_bridge_speed = 50
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = zig-zag
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_flow = 10%
; ironing_pattern = zig-zag
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nLOG_Z\nG92 E0\n
; layer_height = 0.2
; line_width = 0.42
; long_retractions_when_cut = 0
; machine_end_gcode = M141 S0\nM104 S0\nM140 S0\nG1 E-3 F1800\nG0 Z{min(max_print_height, max_layer_z + 3)} F600\nG0 X0 Y0 F12000\n{if max_layer_z < max_print_height / 2}G1 Z{max_print_height / 2 + 10} F600{else}G1 Z{min(max_print_height, max_layer_z + 3)}{endif}
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 5000
; machine_max_acceleration_travel = 0,0
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 2
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 3
; machine_max_speed_e = 30
; machine_max_speed_x = 600
; machine_max_speed_y = 600
; machine_max_speed_z = 10
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = M0
; machine_start_gcode = PRINT_START BED=[hot_plate_temp_initial_layer] HOTEND=[nozzle_temperature_initial_layer] CHAMBER=[chamber_temperature]\nM83\nM140 S[hot_plate_temp_initial_layer]\nM104 S[nozzle_temperature_initial_layer]\nG4 P3000\nG0 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85),0)} Y{max((min(print_bed_max[1] - 5, first_layer_print_min[1] + 80) - 85), 0)} Z5 F6000\nG0 Z[initial_layer_print_height] F600\nG1 E3 F1800\nG1 X{(min(print_bed_max[0], first_layer_print_min[0] + 80))} E{85 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1] - 5, first_layer_print_min[1] + 80) - 85), 0) + 2} E{2 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85), 0)} E{85 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1] - 5, first_layer_print_min[1] + 80) - 85), 0) + 85} E{83 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85), 0) + 2} E{2 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 Y{max((min(print_bed_max[1] - 5, first_layer_print_min[1] + 80) - 85), 0) + 3} E{82 * 0.5 * initial_layer_print_height * nozzle_diameter[0]} F3000\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85), 0) + 3} Z0\nG1 X{max((min(print_bed_max[0], first_layer_print_min[0] + 80) - 85), 0) + 6}\nG1 Z1 F600\n
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.28
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = If you want to use Orca's chamber temperature control feature, check that printer.cfg has added the following M191 macro.\nTo add it: go to Fluidd web interface--configuration, copy the following code to the top of the printer.cfg document, SAVE&RESATART  \n\n[gcode_macro M191]\ngcode:\n    {% set s = params.S|float %}\n    {% if s == 0 %}\n        # If target temperature is 0, do nothing\n        M117 Chamber heating cancelled\n    {% else %}\n        SET_HEATER_TEMPERATURE HEATER=chamber_heater TARGET={s}\n        # Orca: uncomment the following line if you want to use heat bed to assist chamber heating\n        M140 S90\n        TEMPERATURE_WAIT SENSOR=\"heater_generic chamber_heater\" MINIMUM={s-1} MAXIMUM={s+1}\n        M117 Chamber at target temperature\n    {% endif %}
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 210
; nozzle_temperature_initial_layer = 210
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 3000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 95%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.042
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Qidi Q1 Pro 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Qidi Q1 Pro
; printable_area = 0x0,245x0,245x245,0x245
; printable_height = 240
; printer_model = Qidi Q1 Pro
; printer_notes = 
; printer_settings_id = Qidi Q1 Pro 0.4 nozzle - Copy
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 15%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 10
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 4
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 270
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 140x140/PNG, 48x48/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = ;TIMELAPSE_TAKE_FRAME\n
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 3
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 2
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; first_layer_bed_temperature = 60
; bed_shape = 0x0,245x0,245x245,0x245
; first_layer_temperature = 210
; first_layer_height = 0.200
; CONFIG_BLOCK_END


